openapi: 3.1.0

info:
  title: Go2Asia Content Service API
  version: 0.1.0
  description: >
    Downstream API contract for Content Service (M2/M4).

    Notes:
    - Public GET endpoints are accessible via API Gateway.
    - Authorized endpoints (event registration) require gateway-origin auth and asserted user context.

servers:
  - url: https://staging.api.go2asia.space
    description: Staging API Gateway (user-facing paths proxied to downstream)
  - url: https://{workerHost}
    description: Direct service URL (workers.dev / local)
    variables:
      workerHost:
        default: content-service.example

tags:
  - name: health
    description: Service health checks
  - name: content
    description: Atlas/Pulse/Blog public read endpoints
  - name: debug
    description: Debug endpoints (no secrets)

paths:
  /health:
    get:
      tags: [health]
      operationId: getHealth
      summary: Health check
      description: Returns service health status. No auth required.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

  /version:
    get:
      tags: [health]
      operationId: getVersion
      summary: Version (alias of /health)
      description: Returns service version metadata. Alias of /health. No auth required.
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/HealthResponse"

  /v1/content/_debug/db:
    get:
      tags: [debug]
      operationId: debugDb
      summary: Debug DB connectivity and counts (no secrets)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/DebugDbResponse"
        "500":
          $ref: "#/components/responses/InternalError"

  /v1/content/events:
    get:
      tags: [content]
      operationId: listEvents
      summary: List events (public)
      parameters:
        - $ref: "#/components/parameters/Limit"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListEventsResponse"
        "500":
          $ref: "#/components/responses/InternalError"

  /v1/content/events/{id}:
    get:
      tags: [content]
      operationId: getEventById
      summary: Get event by id (public)
      parameters:
        - $ref: "#/components/parameters/EventId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContentEventDto"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /v1/content/events/{id}/register:
    post:
      tags: [content]
      operationId: registerForEvent
      summary: Register current user for event (authorized)
      description: Requires gateway-origin auth and asserted user context.
      security:
        - GatewayAuth: []
      parameters:
        - $ref: "#/components/parameters/XGatewayAuth"
        - $ref: "#/components/parameters/XUserId"
        - $ref: "#/components/parameters/XRequestId"
        - $ref: "#/components/parameters/EventId"
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EventRegistrationResponse"
        "401":
          $ref: "#/components/responses/Unauthorized"
        "409":
          $ref: "#/components/responses/Conflict"
        "500":
          $ref: "#/components/responses/InternalError"

  /v1/content/countries:
    get:
      tags: [content]
      operationId: listCountries
      summary: List countries (public)
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListCountriesResponse"
        "500":
          $ref: "#/components/responses/InternalError"

  /v1/content/cities:
    get:
      tags: [content]
      operationId: listCities
      summary: List cities (public)
      parameters:
        - $ref: "#/components/parameters/CountryId"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListCitiesResponse"
        "500":
          $ref: "#/components/responses/InternalError"

  /v1/content/places:
    get:
      tags: [content]
      operationId: listPlaces
      summary: List places (public)
      parameters:
        - $ref: "#/components/parameters/CityId"
        - $ref: "#/components/parameters/Limit"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListPlacesResponse"
        "500":
          $ref: "#/components/responses/InternalError"

  /v1/content/places/{idOrSlug}:
    get:
      tags: [content]
      operationId: getPlaceByIdOrSlug
      summary: Get place by id or slug (public)
      parameters:
        - $ref: "#/components/parameters/PlaceIdOrSlug"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContentPlaceDto"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

  /v1/content/articles:
    get:
      tags: [content]
      operationId: listArticles
      summary: List articles (public)
      parameters:
        - $ref: "#/components/parameters/Limit"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ListArticlesResponse"
        "500":
          $ref: "#/components/responses/InternalError"

  /v1/content/articles/{slug}:
    get:
      tags: [content]
      operationId: getArticleBySlug
      summary: Get article by slug (public)
      parameters:
        - $ref: "#/components/parameters/ArticleSlug"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContentArticleDto"
        "404":
          $ref: "#/components/responses/NotFound"
        "500":
          $ref: "#/components/responses/InternalError"

components:
  securitySchemes:
    GatewayAuth:
      type: apiKey
      in: header
      name: X-Gateway-Auth
      description: Service JWT issued/forwarded by API Gateway to authenticate gateway-origin requests

  parameters:
    XGatewayAuth:
      name: X-Gateway-Auth
      in: header
      required: true
      schema:
        type: string
    XUserId:
      name: X-User-ID
      in: header
      required: true
      schema:
        type: string
      description: User identifier asserted by API Gateway
    XRequestId:
      name: X-Request-Id
      in: header
      required: false
      schema:
        type: string
    EventId:
      name: id
      in: path
      required: true
      schema:
        type: string
    CountryId:
      name: countryId
      in: query
      required: false
      schema:
        type: string
    CityId:
      name: cityId
      in: query
      required: false
      schema:
        type: string
    PlaceIdOrSlug:
      name: idOrSlug
      in: path
      required: true
      schema:
        type: string
    ArticleSlug:
      name: slug
      in: path
      required: true
      schema:
        type: string
    Limit:
      name: limit
      in: query
      required: false
      schema:
        type: integer
        minimum: 1
        maximum: 200

  responses:
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    NotFound:
      description: Not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    Conflict:
      description: Conflict
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
    InternalError:
      description: Internal server error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"

  schemas:
    HealthResponse:
      type: object
      required: [service, env, status, version]
      properties:
        service:
          type: string
          example: content-service
        env:
          type: string
          example: staging
        status:
          type: string
          example: ok
        version:
          type: string
          example: "<sha>"

    ErrorResponse:
      type: object
      required: [error]
      properties:
        error:
          type: string
          example: "InternalError"
        message:
          type: string
        requestId:
          type: string

    DebugDbResponse:
      type: object
      required: [ok]
      properties:
        ok:
          type: boolean
        error:
          type: object
          nullable: true
          additionalProperties: true
        counts:
          type: object
          nullable: true
          additionalProperties:
            type: integer

    ListEventsResponse:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/ContentEventDto"

    ListCountriesResponse:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/ContentCountryDto"

    ListCitiesResponse:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/ContentCityDto"

    ListPlacesResponse:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/ContentPlaceDto"

    ListArticlesResponse:
      type: object
      required: [items]
      properties:
        items:
          type: array
          items:
            $ref: "#/components/schemas/ContentArticleDto"

    EventRegistrationResponse:
      type: object
      required: [ok, registrationId, eventId, userId]
      properties:
        ok:
          type: boolean
        registrationId:
          type: string
        eventId:
          type: string
        userId:
          type: string

    ContentEventDto:
      type: object
      required: [id, title, slug, startDate, isActive]
      properties:
        id:
          type: string
        title:
          type: string
        slug:
          type: string
        description:
          type: string
          nullable: true
        category:
          type: string
          nullable: true
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
          nullable: true
        location:
          type: string
          nullable: true
        latitude:
          type: string
          nullable: true
        longitude:
          type: string
          nullable: true
        imageUrl:
          type: string
          nullable: true
        isActive:
          type: boolean

    ContentCountryDto:
      type: object
      required: [id, slug, name, code, citiesCount, placesCount]
      properties:
        id:
          type: string
        slug:
          type: string
        name:
          type: string
        code:
          type: string
        flag:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        heroImage:
          type: string
          nullable: true
        citiesCount:
          type: integer
        placesCount:
          type: integer

    ContentCityDto:
      type: object
      required: [id, slug, name, countryId, placesCount]
      properties:
        id:
          type: string
        slug:
          type: string
        name:
          type: string
        countryId:
          type: string
        countryName:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        placesCount:
          type: integer
        latitude:
          type: string
          nullable: true
        longitude:
          type: string
          nullable: true
        heroImage:
          type: string
          nullable: true

    ContentPlaceDto:
      type: object
      required: [id, slug, name, type, photos]
      properties:
        id:
          type: string
        slug:
          type: string
        name:
          type: string
        type:
          type: string
        description:
          type: string
          nullable: true
        country:
          type: string
          nullable: true
        city:
          type: string
          nullable: true
        address:
          type: string
          nullable: true
        latitude:
          type: string
          nullable: true
        longitude:
          type: string
          nullable: true
        heroImage:
          type: string
          nullable: true
        photos:
          type: array
          items:
            type: string

    ContentArticleDto:
      type: object
      required: [id, slug, title, content, status]
      properties:
        id:
          type: string
        slug:
          type: string
        title:
          type: string
        excerpt:
          type: string
          nullable: true
        content:
          type: string
        category:
          type: string
          nullable: true
        tags:
          type: array
          nullable: true
          items:
            type: string
        coverImage:
          type: string
          nullable: true
        publishedAt:
          type: string
          format: date-time
          nullable: true
        status:
          type: string



