/**
 * Guru Asia - Mock Objects
 * Демо-данные для разработки и тестирования
 * Локация: Новосибирск, центр (~54.9833, 82.8964)
 */

import type {
  GuruObject,
  PlaceObject,
  EventObject,
  HousingObject,
  PersonObject,
  QuestObject,
} from './types';

// =============================================================================
// Места (Atlas) - 15 объектов
// =============================================================================

const places: PlaceObject[] = [
  {
    id: 'place-1',
    type: 'place',
    title: 'Coffee Bean',
    description: 'Уютная кофейня с авторским кофе и десертами',
    cover: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=400',
    lat: 54.9845,
    lng: 82.8978,
    address: 'ул. Ленина, 12',
    city: 'Новосибирск',
    categories: ['cafe', 'coffee'],
    priceLevel: 1,
    isOpen: true,
    openingHours: '08:00 – 22:00',
    hasWifi: true,
    hasPowerOutlets: true,
    hasCoffee: true,
    isQuiet: false,
    rating: 4.7,
    popularity: 156,
    isRF: true,
    isVerified: true,
    updatedAt: '2025-11-20T10:00:00Z',
  },
  {
    id: 'place-2',
    type: 'place',
    title: 'Коворкинг "Хаб"',
    description: 'Современное рабочее пространство для фрилансеров и стартапов',
    cover: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=400',
    lat: 54.9820,
    lng: 82.8920,
    address: 'ул. Советская, 25',
    city: 'Новосибирск',
    categories: ['coworking', 'work'],
    priceLevel: 2,
    isOpen: true,
    openingHours: '09:00 – 21:00',
    hasWifi: true,
    hasPowerOutlets: true,
    hasCoffee: true,
    isQuiet: true,
    rating: 4.8,
    popularity: 89,
    isRF: true,
    isVerified: true,
    updatedAt: '2025-11-22T14:30:00Z',
  },
  {
    id: 'place-3',
    type: 'place',
    title: 'Кофейня "Бодрый День"',
    description: 'Завтраки и бранчи с видом на набережную',
    cover: 'https://images.unsplash.com/photo-1554118811-1e0d58224f24?w=400',
    lat: 54.9810,
    lng: 82.9010,
    address: 'Набережная, 5',
    city: 'Новосибирск',
    categories: ['cafe', 'breakfast'],
    priceLevel: 2,
    isOpen: true,
    openingHours: '07:00 – 20:00',
    hasWifi: true,
    hasPowerOutlets: false,
    hasCoffee: true,
    isQuiet: false,
    rating: 4.5,
    popularity: 234,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-18T09:00:00Z',
  },
  {
    id: 'place-4',
    type: 'place',
    title: 'Музей Города',
    description: 'История Новосибирска от основания до наших дней',
    cover: 'https://images.unsplash.com/photo-1554907984-15263bfd63bd?w=400',
    lat: 54.9870,
    lng: 82.9050,
    address: 'Красный проспект, 23',
    city: 'Новосибирск',
    categories: ['museum', 'culture'],
    priceLevel: 1,
    isOpen: false,
    openingHours: '10:00 – 18:00',
    opensAt: '10:00',
    hasWifi: true,
    hasPowerOutlets: false,
    hasCoffee: false,
    isQuiet: true,
    rating: 4.6,
    popularity: 312,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-15T11:00:00Z',
  },
  {
    id: 'place-5',
    type: 'place',
    title: 'Парк Культуры',
    description: 'Центральный парк с детскими площадками и аттракционами',
    cover: 'https://images.unsplash.com/photo-1568515387631-8b650bbcdb90?w=400',
    lat: 54.9900,
    lng: 82.8900,
    address: 'ул. Парковая, 1',
    city: 'Новосибирск',
    categories: ['park', 'family'],
    priceLevel: 1,
    isOpen: true,
    openingHours: '06:00 – 23:00',
    hasWifi: false,
    hasPowerOutlets: false,
    hasCoffee: false,
    isQuiet: false,
    isKidFriendly: true,
    rating: 4.4,
    popularity: 567,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-10T08:00:00Z',
  },
  {
    id: 'place-6',
    type: 'place',
    title: 'Коворкинг "Рабочее Место"',
    description: 'Тихий коворкинг для сосредоточенной работы',
    cover: 'https://images.unsplash.com/photo-1527192491265-7e15c55b1ed2?w=400',
    lat: 54.9855,
    lng: 82.8945,
    address: 'ул. Державина, 18',
    city: 'Новосибирск',
    categories: ['coworking', 'work'],
    priceLevel: 2,
    isOpen: true,
    openingHours: '08:00 – 22:00',
    hasWifi: true,
    hasPowerOutlets: true,
    hasCoffee: true,
    isQuiet: true,
    rating: 4.8,
    popularity: 78,
    isRF: true,
    isVerified: false,
    updatedAt: '2025-11-24T16:00:00Z',
  },
  {
    id: 'place-7',
    type: 'place',
    title: 'Ресторан "Вкус Азии"',
    description: 'Паназиатская кухня: суши, воки, том ям',
    cover: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=400',
    lat: 54.9805,
    lng: 82.8880,
    address: 'ул. Орджоникидзе, 33',
    city: 'Новосибирск',
    categories: ['restaurant', 'asian', 'food'],
    priceLevel: 2,
    isOpen: true,
    openingHours: '11:00 – 23:00',
    hasWifi: true,
    hasPowerOutlets: false,
    hasCoffee: false,
    isQuiet: false,
    rating: 4.3,
    popularity: 189,
    isRF: true,
    isVerified: true,
    updatedAt: '2025-11-21T12:00:00Z',
  },
  {
    id: 'place-8',
    type: 'place',
    title: 'Библиотека им. Пушкина',
    description: 'Главная городская библиотека с читальными залами',
    cover: 'https://images.unsplash.com/photo-1521587760476-6c12a4b040da?w=400',
    lat: 54.9790,
    lng: 82.9000,
    address: 'ул. Пушкина, 7',
    city: 'Новосибирск',
    categories: ['library', 'culture'],
    priceLevel: 1,
    isOpen: false,
    openingHours: '09:00 – 19:00',
    hasWifi: true,
    hasPowerOutlets: true,
    hasCoffee: false,
    isQuiet: true,
    rating: 4.5,
    popularity: 145,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-05T10:00:00Z',
  },
  {
    id: 'place-9',
    type: 'place',
    title: 'Спортзал "Энергия"',
    description: 'Фитнес-центр с бассейном и тренажёрным залом',
    cover: 'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=400',
    lat: 54.9815,
    lng: 82.8850,
    address: 'ул. Спортивная, 15',
    city: 'Новосибирск',
    categories: ['gym', 'sport', 'fitness'],
    priceLevel: 2,
    isOpen: true,
    openingHours: '06:00 – 23:00',
    hasWifi: true,
    hasPowerOutlets: false,
    hasCoffee: false,
    isQuiet: false,
    rating: 4.2,
    popularity: 234,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-19T07:00:00Z',
  },
  {
    id: 'place-10',
    type: 'place',
    title: 'Кинотеатр "Мир"',
    description: 'Многозальный кинотеатр с IMAX и Dolby Atmos',
    cover: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?w=400',
    lat: 54.9750,
    lng: 82.8930,
    address: 'пр. Маркса, 45',
    city: 'Новосибирск',
    categories: ['cinema', 'entertainment'],
    priceLevel: 2,
    isOpen: true,
    openingHours: '10:00 – 01:00',
    hasWifi: true,
    hasPowerOutlets: false,
    hasCoffee: true,
    isQuiet: false,
    rating: 4.4,
    popularity: 456,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-23T15:00:00Z',
  },
  {
    id: 'place-11',
    type: 'place',
    title: 'Антикафе "Время"',
    description: 'Платишь за время, напитки и снеки бесплатно',
    cover: 'https://images.unsplash.com/photo-1559925393-8be0ec4767c8?w=400',
    lat: 54.9860,
    lng: 82.9020,
    address: 'ул. Фрунзе, 10',
    city: 'Новосибирск',
    categories: ['anticafe', 'coworking'],
    priceLevel: 1,
    isOpen: true,
    openingHours: '10:00 – 00:00',
    hasWifi: true,
    hasPowerOutlets: true,
    hasCoffee: true,
    isQuiet: false,
    isKidFriendly: true,
    rating: 4.6,
    popularity: 123,
    isRF: true,
    isVerified: false,
    updatedAt: '2025-11-24T18:00:00Z',
  },
  {
    id: 'place-12',
    type: 'place',
    title: 'Бар "Пивная Точка"',
    description: 'Крафтовое пиво и закуски в центре города',
    cover: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=400',
    lat: 54.9825,
    lng: 82.8995,
    address: 'ул. Гоголя, 28',
    city: 'Новосибирск',
    categories: ['bar', 'nightlife'],
    priceLevel: 2,
    isOpen: false,
    openingHours: '18:00 – 02:00',
    opensAt: '18:00',
    hasWifi: true,
    hasPowerOutlets: false,
    hasCoffee: false,
    isQuiet: false,
    rating: 4.3,
    popularity: 178,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-22T20:00:00Z',
  },
  {
    id: 'place-13',
    type: 'place',
    title: 'Пекарня "Хлебное Место"',
    description: 'Свежая выпечка и кофе на вынос',
    cover: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400',
    lat: 54.9838,
    lng: 82.8890,
    address: 'ул. Чаплыгина, 5',
    city: 'Новосибирск',
    categories: ['bakery', 'cafe'],
    priceLevel: 1,
    isOpen: true,
    openingHours: '07:00 – 21:00',
    hasWifi: false,
    hasPowerOutlets: false,
    hasCoffee: true,
    isQuiet: false,
    rating: 4.8,
    popularity: 267,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-25T06:00:00Z',
  },
  {
    id: 'place-14',
    type: 'place',
    title: 'Йога-студия "Гармония"',
    description: 'Хатха, виньяса, медитация',
    cover: 'https://images.unsplash.com/photo-1545205597-3d9d02c29597?w=400',
    lat: 54.9880,
    lng: 82.8970,
    address: 'ул. Мира, 3',
    city: 'Новосибирск',
    categories: ['yoga', 'sport', 'wellness'],
    priceLevel: 2,
    isOpen: true,
    openingHours: '07:00 – 21:00',
    hasWifi: true,
    hasPowerOutlets: false,
    hasCoffee: false,
    isQuiet: true,
    rating: 4.9,
    popularity: 98,
    isRF: true,
    isVerified: true,
    updatedAt: '2025-11-24T07:00:00Z',
  },
  {
    id: 'place-15',
    type: 'place',
    title: 'Детский центр "Радуга"',
    description: 'Развивающие занятия для детей от 1 до 10 лет',
    cover: 'https://images.unsplash.com/photo-1576495199011-eb94736d05d6?w=400',
    lat: 54.9795,
    lng: 82.9035,
    address: 'ул. Детская, 12',
    city: 'Новосибирск',
    categories: ['kids', 'education', 'family'],
    priceLevel: 2,
    isOpen: false,
    openingHours: '09:00 – 19:00',
    hasWifi: true,
    hasPowerOutlets: false,
    hasCoffee: false,
    isQuiet: false,
    isKidFriendly: true,
    rating: 4.7,
    popularity: 145,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-20T09:00:00Z',
  },
];

// =============================================================================
// События (Pulse) - 8 объектов
// =============================================================================

const events: EventObject[] = [
  {
    id: 'event-1',
    type: 'event',
    title: 'Yoga Sunrise Session',
    description: 'Утренняя йога на свежем воздухе в парке',
    cover: 'https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400',
    lat: 54.9895,
    lng: 82.8905,
    address: 'Парк Культуры',
    city: 'Новосибирск',
    categories: ['sport', 'wellness'],
    startDate: new Date().toISOString(),
    isHappeningNow: true,
    organizer: 'Йога-студия "Гармония"',
    isFree: true,
    rating: 4.8,
    popularity: 45,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-24T06:00:00Z',
  },
  {
    id: 'event-2',
    type: 'event',
    title: 'Meetup "IT в Новосибирске"',
    description: 'Нетворкинг для IT-специалистов: доклады, общение, пицца',
    cover: 'https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=400',
    lat: 54.9820,
    lng: 82.8922,
    address: 'Коворкинг "Хаб"',
    city: 'Новосибирск',
    categories: ['it', 'community', 'networking'],
    startDate: new Date(Date.now() + 6 * 60 * 60 * 1000).toISOString(), // +6 часов
    isHappeningNow: false,
    organizer: 'NSK IT Community',
    organizerId: 'org-1',
    isFree: false,
    price: '500 ₽',
    rating: 4.9,
    popularity: 89,
    isRF: true,
    isVerified: true,
    updatedAt: '2025-11-23T12:00:00Z',
  },
  {
    id: 'event-3',
    type: 'event',
    title: 'Концерт в парке',
    description: 'Живая музыка: джаз и блюз под открытым небом',
    cover: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400',
    lat: 54.9902,
    lng: 82.8895,
    address: 'Парк Культуры, главная сцена',
    city: 'Новосибирск',
    categories: ['music', 'culture'],
    startDate: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(), // завтра
    isHappeningNow: false,
    organizer: 'Администрация парка',
    isFree: false,
    price: '300 ₽',
    rating: 4.5,
    popularity: 234,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-22T10:00:00Z',
  },
  {
    id: 'event-4',
    type: 'event',
    title: 'Экскурсия по городу',
    description: 'Пешая прогулка по историческому центру Новосибирска',
    cover: 'https://images.unsplash.com/photo-1569880153113-76e33fc52d5f?w=400',
    lat: 54.9833,
    lng: 82.8964,
    address: 'Площадь Ленина, у памятника',
    city: 'Новосибирск',
    categories: ['culture', 'tour'],
    startDate: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(), // +3 часа
    isHappeningNow: false,
    organizer: 'Гид Анна',
    organizerId: 'person-3',
    isFree: false,
    price: '800 ₽',
    rating: 5.0,
    popularity: 56,
    isRF: true,
    isVerified: true,
    updatedAt: '2025-11-24T08:00:00Z',
  },
  {
    id: 'event-5',
    type: 'event',
    title: 'Фестиваль еды',
    description: 'Уличная еда от лучших ресторанов города',
    cover: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=400',
    lat: 54.9850,
    lng: 82.8870,
    address: 'Площадь Свердлова',
    city: 'Новосибирск',
    categories: ['food', 'festival'],
    startDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000).toISOString(), // через 2 дня
    endDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    isHappeningNow: false,
    organizer: 'Мэрия Новосибирска',
    isFree: true,
    rating: 4.4,
    popularity: 567,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-20T14:00:00Z',
  },
  {
    id: 'event-6',
    type: 'event',
    title: 'Мастер-класс по кофе',
    description: 'Научитесь готовить эспрессо как профессиональный бариста',
    cover: 'https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=400',
    lat: 54.9845,
    lng: 82.8980,
    address: 'Coffee Bean',
    city: 'Новосибирск',
    categories: ['education', 'food'],
    startDate: new Date(Date.now() + 48 * 60 * 60 * 1000).toISOString(), // через 2 дня
    isHappeningNow: false,
    organizer: 'Coffee Bean',
    isFree: false,
    price: '1500 ₽',
    rating: 4.9,
    popularity: 34,
    isRF: true,
    isVerified: false,
    updatedAt: '2025-11-23T11:00:00Z',
  },
  {
    id: 'event-7',
    type: 'event',
    title: 'Киновечер: Азиатское кино',
    description: 'Показ корейского фильма с субтитрами + обсуждение',
    cover: 'https://images.unsplash.com/photo-1536440136628-849c177e76a1?w=400',
    lat: 54.9860,
    lng: 82.9022,
    address: 'Антикафе "Время"',
    city: 'Новосибирск',
    categories: ['culture', 'cinema', 'community'],
    startDate: new Date(Date.now() + 8 * 60 * 60 * 1000).toISOString(), // +8 часов
    isHappeningNow: false,
    organizer: 'Клуб любителей Азии',
    isFree: false,
    price: '200 ₽ + время',
    rating: 4.7,
    popularity: 28,
    isRF: true,
    isVerified: false,
    updatedAt: '2025-11-24T10:00:00Z',
  },
  {
    id: 'event-8',
    type: 'event',
    title: 'Утренняя пробежка',
    description: 'Бегаем вместе по набережной каждое утро',
    cover: 'https://images.unsplash.com/photo-1552674605-db6ffd4facb5?w=400',
    lat: 54.9810,
    lng: 82.9015,
    address: 'Набережная, у моста',
    city: 'Новосибирск',
    categories: ['sport', 'community'],
    startDate: new Date().toISOString(),
    isHappeningNow: true,
    organizer: 'Running Club NSK',
    isFree: true,
    rating: 4.6,
    popularity: 78,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-25T05:00:00Z',
  },
];

// =============================================================================
// Жильё (AIRent NSK) - 5 объектов
// =============================================================================

const housing: HousingObject[] = [
  {
    id: 'housing-1',
    type: 'housing',
    title: 'Уютная 2-комнатная квартира в центре',
    description: 'Светлая квартира с видом на Красный проспект, рядом метро',
    cover: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=400',
    lat: 54.9840,
    lng: 82.8955,
    address: 'ул. Ленина, 8',
    city: 'Новосибирск',
    housingType: 'apartment',
    pricePerNight: 3500,
    priceLevel: 2,
    availableNow: true,
    rooms: 2,
    area: 58,
    rating: 4.8,
    popularity: 45,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-24T12:00:00Z',
  },
  {
    id: 'housing-2',
    type: 'housing',
    title: 'Студия в центре',
    description: 'Компактная студия для одного или пары, отличный ремонт',
    cover: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400',
    lat: 54.9825,
    lng: 82.8990,
    address: 'ул. Советская, 10',
    city: 'Новосибирск',
    housingType: 'apartment',
    pricePerNight: 2000,
    priceLevel: 1,
    availableNow: true,
    rooms: 1,
    area: 28,
    rating: 4.5,
    popularity: 67,
    isRF: true,
    isVerified: true,
    updatedAt: '2025-11-23T15:00:00Z',
  },
  {
    id: 'housing-3',
    type: 'housing',
    title: 'Хостел "Путешественник"',
    description: 'Бюджетное размещение в центре, общая кухня, лаундж',
    cover: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=400',
    lat: 54.9815,
    lng: 82.8930,
    address: 'ул. Гоголя, 15',
    city: 'Новосибирск',
    housingType: 'hostel',
    pricePerNight: 800,
    priceLevel: 1,
    availableNow: true,
    rating: 4.2,
    popularity: 123,
    isRF: true,
    isVerified: true,
    updatedAt: '2025-11-22T18:00:00Z',
  },
  {
    id: 'housing-4',
    type: 'housing',
    title: 'Комната в апартаментах',
    description: 'Отдельная комната с общей кухней и ванной',
    cover: 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=400',
    lat: 54.9870,
    lng: 82.8920,
    address: 'ул. Державина, 25',
    city: 'Новосибирск',
    housingType: 'room',
    pricePerNight: 1200,
    priceLevel: 1,
    availableNow: false,
    availableFrom: '2025-11-28',
    rating: 4.0,
    popularity: 34,
    isRF: false,
    isVerified: false,
    updatedAt: '2025-11-20T10:00:00Z',
  },
  {
    id: 'housing-5',
    type: 'housing',
    title: 'Отель "Центральный"',
    description: 'Комфортный номер в гостинице 4*, завтрак включён',
    cover: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=400',
    lat: 54.9855,
    lng: 82.9000,
    address: 'Красный проспект, 50',
    city: 'Новосибирск',
    housingType: 'hotel',
    pricePerNight: 6500,
    priceLevel: 3,
    availableNow: true,
    rating: 4.6,
    popularity: 89,
    isRF: true,
    isVerified: true,
    updatedAt: '2025-11-24T09:00:00Z',
  },
];

// =============================================================================
// Люди/PRO (Space) - 5 объектов
// =============================================================================

const people: PersonObject[] = [
  {
    id: 'person-1',
    type: 'person',
    title: 'Дмитрий — Местный эксперт',
    displayName: 'Дмитрий',
    description: 'Знаю все секретные места Новосибирска. Помогу с релокацией.',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    cover: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400',
    lat: 54.9841,
    lng: 82.8968,
    city: 'Новосибирск',
    bio: 'Живу в Новосибирске 15 лет. IT-специалист, фрилансер. Люблю кофе и пешие прогулки.',
    isPRO: true,
    isMentor: true,
    isGuide: false,
    isAvailableNow: true,
    rating: 4.9,
    popularity: 156,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-24T08:00:00Z',
  },
  {
    id: 'person-2',
    type: 'person',
    title: 'Елена — Риелтор',
    displayName: 'Елена',
    description: 'Помогу найти жильё в Новосибирске: аренда и покупка.',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    cover: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=400',
    lat: 54.9830,
    lng: 82.8950,
    city: 'Новосибирск',
    bio: 'Риелтор с 10-летним опытом. Специализируюсь на центре города.',
    isPRO: true,
    isMentor: false,
    isGuide: false,
    isAvailableNow: true,
    rating: 4.7,
    popularity: 89,
    isRF: true,
    isVerified: true,
    updatedAt: '2025-11-23T14:00:00Z',
  },
  {
    id: 'person-3',
    type: 'person',
    title: 'Анна — Гид по Новосибирску',
    displayName: 'Анна',
    description: 'Проведу авторскую экскурсию по городу на русском или английском.',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    cover: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=400',
    lat: 54.9835,
    lng: 82.8985,
    city: 'Новосибирск',
    bio: 'Историк, влюблённая в свой город. Экскурсии с душой!',
    isPRO: true,
    isMentor: false,
    isGuide: true,
    isAvailableNow: true,
    rating: 5.0,
    popularity: 234,
    isRF: true,
    isVerified: true,
    updatedAt: '2025-11-24T09:00:00Z',
  },
  {
    id: 'person-4',
    type: 'person',
    title: 'Алексей — IT-ментор',
    displayName: 'Алексей',
    description: 'Помогу войти в IT: карьерные консультации, ревью резюме.',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
    cover: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=400',
    lat: 54.9822,
    lng: 82.8925,
    city: 'Новосибирск',
    bio: 'Senior Developer в Яндексе. 8 лет в индустрии.',
    isPRO: true,
    isMentor: true,
    isGuide: false,
    isAvailableNow: false,
    availableUntil: '2025-11-25T18:00:00Z',
    rating: 4.8,
    popularity: 178,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-22T16:00:00Z',
  },
  {
    id: 'person-5',
    type: 'person',
    title: 'Анна Смирнова — Фотограф',
    displayName: 'Анна С.',
    description: 'Фотосессии в красивых местах Новосибирска. Портреты, love story.',
    avatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400',
    cover: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb?w=400',
    lat: 54.9850,
    lng: 82.9010,
    city: 'Новосибирск',
    bio: 'Профессиональный фотограф. Снимаю людей и город.',
    isPRO: true,
    isMentor: false,
    isGuide: false,
    isAvailableNow: false,
    rating: 4.9,
    popularity: 145,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-23T11:00:00Z',
  },
];

// =============================================================================
// Квесты (Quest Asia) - 3 объекта
// =============================================================================

const quests: QuestObject[] = [
  {
    id: 'quest-1',
    type: 'quest',
    title: 'Историческая прогулка',
    description: 'Пройди по следам основателей города, найди все памятные места',
    cover: 'https://images.unsplash.com/photo-1569880153113-76e33fc52d5f?w=400',
    lat: 54.9833,
    lng: 82.8964,
    address: 'Старт: Площадь Ленина',
    city: 'Новосибирск',
    level: 'beginner',
    duration: 60,
    checkpointsCount: 8,
    hasRewards: true,
    rewards: '50 Points + NFT "Историк"',
    isNew: false,
    isTrending: true,
    rating: 4.7,
    popularity: 234,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-15T10:00:00Z',
  },
  {
    id: 'quest-2',
    type: 'quest',
    title: 'Секреты старого города',
    description: 'Найди скрытые дворики и необычные здания центра',
    cover: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?w=400',
    lat: 54.9860,
    lng: 82.8940,
    address: 'Старт: у Оперного театра',
    city: 'Новосибирск',
    level: 'advanced',
    duration: 90,
    checkpointsCount: 12,
    hasRewards: true,
    rewards: '100 Points + NFT "Исследователь"',
    isNew: true,
    isTrending: false,
    rating: 4.9,
    popularity: 89,
    isRF: false,
    isVerified: true,
    updatedAt: '2025-11-22T14:00:00Z',
  },
  {
    id: 'quest-3',
    type: 'quest',
    title: 'Фото-охота',
    description: 'Сфотографируй 10 локаций по подсказкам и загрузи в приложение',
    cover: 'https://images.unsplash.com/photo-1452587925148-ce544e77e70d?w=400',
    lat: 54.9820,
    lng: 82.9000,
    address: 'Старт: Первомайский сквер',
    city: 'Новосибирск',
    level: 'beginner',
    duration: 30,
    checkpointsCount: 10,
    hasRewards: true,
    rewards: '30 Points',
    isNew: false,
    isTrending: false,
    rating: 4.5,
    popularity: 156,
    isRF: false,
    isVerified: false,
    updatedAt: '2025-11-18T09:00:00Z',
  },
];

// =============================================================================
// Экспорт
// =============================================================================

/** Все объекты Guru Asia */
export const mockObjects: GuruObject[] = [
  ...places,
  ...events,
  ...housing,
  ...people,
  ...quests,
];

/** Объекты по типам */
export const mockPlaces = places;
export const mockEvents = events;
export const mockHousing = housing;
export const mockPeople = people;
export const mockQuests = quests;

/** Центр карты по умолчанию (Новосибирск) */
export const DEFAULT_CENTER = {
  lat: 54.9833,
  lng: 82.8964,
};

/** Количество объектов по типам */
export const OBJECT_COUNTS = {
  places: places.length,
  events: events.length,
  housing: housing.length,
  people: people.length,
  quests: quests.length,
  total: mockObjects.length,
};

