/**
 * @go2asia/sdk
 * 
 * Auto-generated API client SDK from OpenAPI specifications.
 * 
 * This file is auto-generated by Orval. Do not edit manually.
 * Run `pnpm gen:sdk` to regenerate.
 */

// SDK will be generated here by Orval
export {};







