/**
 * Generated by orval v7.17.0 🍺
 * Do not edit manually.
 * Go2Asia Platform API
 * Unified API specification for all Go2Asia backend microservices. This file defines the global schema and shared components. Each microservice extends this file via modular OpenAPI fragments.

 * OpenAPI spec version: 0.1.0
 */
import type {
  AddPointsRequest,
  AddPointsResponse,
  AddQuestStepRequest,
  AttachMediaUsageRequest,
  AttachMediaUsageResponse,
  AttachSpacePostMediaRequest,
  BadRequestResponse,
  ClaimReferralRequest,
  ClaimReferralResponse,
  ClerkWebhook200,
  ClerkWebhookBody,
  ConflictResponse,
  ContentArticleDto,
  ContentBlogPostDetailDto,
  ContentEventDto,
  ContentPlaceDto,
  CreateQuestRequest,
  CreateSpaceGroupRequest,
  CreateSpacePostRequest,
  CreateSpaceRepostRequest,
  CreateUploadTokenRequest,
  CreateUploadTokenResponse,
  CursorListBlogPostsResponse,
  DebugDbResponse,
  EnsureUserRequest,
  EnsureUserResponse,
  EventRegistrationResponse,
  GenerateCodeRequest,
  GenerateCodeResponse,
  GetReferralTreeParams,
  GetSpaceActivityFeedParams,
  GetSpaceGroupFeedParams,
  GetSpaceHomeFeedParams,
  GetSpaceProfileFeedParams,
  InternalErrorResponse,
  LinkReferralRequest,
  LinkReferralResponse,
  ListArticlesParams,
  ListArticlesResponse,
  ListBlogPostsParams,
  ListCitiesParams,
  ListCitiesResponse,
  ListCityTabsParams,
  ListContentTabsResponse,
  ListCountriesResponse,
  ListCountryTabsParams,
  ListEventsParams,
  ListEventsResponse,
  ListPlacesParams,
  ListPlacesResponse,
  ListPointsTransactionsParams,
  ListQuestSubmissionsParams,
  ListQuestsParams,
  MarkFirstLoginRequest,
  MarkFirstLoginResponse,
  NotFoundResponse,
  QuestConflictResponse,
  QuestDetailResponse,
  QuestForbiddenResponse,
  QuestInternalErrorResponse,
  QuestListResponse,
  QuestNotFoundResponse,
  QuestProgressResponse,
  QuestServiceAuthNotConfiguredResponse,
  QuestStepResponse,
  QuestSubmissionListResponse,
  QuestSubmissionResponse,
  QuestUnauthorizedResponse,
  QuestValidationErrorResponse,
  RateLimitedResponse,
  ReferralCodeResponse,
  ReferralStatsResponse,
  ReferralTreeResponse,
  ReviewSubmissionRequest,
  ServiceAuthNotConfiguredResponse,
  ServiceNotConfiguredResponse,
  SpaceActivityFeedResponse,
  SpaceFeedResponse,
  SpaceForbiddenResponse,
  SpaceGroupMembershipResponse,
  SpaceGroupResponse,
  SpacePostMediaAttachmentResponse,
  SpacePostResponse,
  SpaceProfileResponse,
  SpaceRateLimitedResponse,
  SpaceServiceAuthNotConfiguredResponse,
  SpaceValidationErrorResponse,
  SubmitQuestStepRequest,
  TransactionsPage,
  UnauthorizedResponse,
  UploadResult,
  UserBalance,
} from "../packages/sdk/src/generated";

import { customInstance } from "../packages/sdk/src/mutator";

/**
 * Idempotency policy (M3): - `externalId` is required and MUST be globally unique for Points Service. - If `externalId` already exists and payload differs (`amount` and/or `action`) => 409 Conflict and the event MUST be logged as an integration error.
Limits policy (M3): - Per-action limits and a simple configurable per-user velocity cap are applied inside Points Service.

 * @summary Add points to a user (idempotent)
 */
export type addPointsResponse200 = {
  data: AddPointsResponse;
  status: 200;
};

export type addPointsResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type addPointsResponse409 = {
  data: ConflictResponse;
  status: 409;
};

export type addPointsResponse429 = {
  data: RateLimitedResponse;
  status: 429;
};

export type addPointsResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type addPointsResponse503 = {
  data: ServiceAuthNotConfiguredResponse;
  status: 503;
};

export type addPointsResponseSuccess = addPointsResponse200 & {
  headers: Headers;
};
export type addPointsResponseError = (
  | addPointsResponse401
  | addPointsResponse409
  | addPointsResponse429
  | addPointsResponse500
  | addPointsResponse503
) & {
  headers: Headers;
};

export type addPointsResponse = addPointsResponseSuccess | addPointsResponseError;

export const getAddPointsUrl = () => {
  return `/internal/points/add`;
};

export const addPoints = async (
  addPointsRequest: AddPointsRequest,
  options?: RequestInit
): Promise<addPointsResponse> => {
  return customInstance<addPointsResponse>(getAddPointsUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(addPointsRequest),
  });
};

/**
 * Idempotent upsert of referral code for the given userId.
 * @summary Ensure referral code exists for user (idempotent)
 */
export type generateReferralCodeResponse200 = {
  data: GenerateCodeResponse;
  status: 200;
};

export type generateReferralCodeResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type generateReferralCodeResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type generateReferralCodeResponse503 = {
  data: ServiceAuthNotConfiguredResponse;
  status: 503;
};

export type generateReferralCodeResponseSuccess = generateReferralCodeResponse200 & {
  headers: Headers;
};
export type generateReferralCodeResponseError = (
  | generateReferralCodeResponse401
  | generateReferralCodeResponse500
  | generateReferralCodeResponse503
) & {
  headers: Headers;
};

export type generateReferralCodeResponse =
  | generateReferralCodeResponseSuccess
  | generateReferralCodeResponseError;

export const getGenerateReferralCodeUrl = () => {
  return `/internal/referral/generate-code`;
};

export const generateReferralCode = async (
  generateCodeRequest: GenerateCodeRequest,
  options?: RequestInit
): Promise<generateReferralCodeResponse> => {
  return customInstance<generateReferralCodeResponse>(getGenerateReferralCodeUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(generateCodeRequest),
  });
};

/**
 * Invariant (M3): referee can have at most one referrer (L1 link).

 * @summary Link referee to referrer by referral code
 */
export type linkReferralResponse200 = {
  data: LinkReferralResponse;
  status: 200;
};

export type linkReferralResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type linkReferralResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type linkReferralResponse409 = {
  data: ConflictResponse;
  status: 409;
};

export type linkReferralResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type linkReferralResponse503 = {
  data: ServiceAuthNotConfiguredResponse;
  status: 503;
};

export type linkReferralResponseSuccess = linkReferralResponse200 & {
  headers: Headers;
};
export type linkReferralResponseError = (
  | linkReferralResponse401
  | linkReferralResponse404
  | linkReferralResponse409
  | linkReferralResponse500
  | linkReferralResponse503
) & {
  headers: Headers;
};

export type linkReferralResponse = linkReferralResponseSuccess | linkReferralResponseError;

export const getLinkReferralUrl = () => {
  return `/internal/referral/link`;
};

export const linkReferral = async (
  linkReferralRequest: LinkReferralRequest,
  options?: RequestInit
): Promise<linkReferralResponse> => {
  return customInstance<linkReferralResponse>(getLinkReferralUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(linkReferralRequest),
  });
};

/**
 * Service-to-service endpoint to mark referral relation as active by setting first_login_at for the given userId (referee).

 * @summary Mark referee first login (idempotent)
 */
export type markReferralFirstLoginResponse200 = {
  data: MarkFirstLoginResponse;
  status: 200;
};

export type markReferralFirstLoginResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type markReferralFirstLoginResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type markReferralFirstLoginResponse503 = {
  data: ServiceAuthNotConfiguredResponse;
  status: 503;
};

export type markReferralFirstLoginResponseSuccess = markReferralFirstLoginResponse200 & {
  headers: Headers;
};
export type markReferralFirstLoginResponseError = (
  | markReferralFirstLoginResponse401
  | markReferralFirstLoginResponse500
  | markReferralFirstLoginResponse503
) & {
  headers: Headers;
};

export type markReferralFirstLoginResponse =
  | markReferralFirstLoginResponseSuccess
  | markReferralFirstLoginResponseError;

export const getMarkReferralFirstLoginUrl = () => {
  return `/internal/referral/mark-first-login`;
};

export const markReferralFirstLogin = async (
  markFirstLoginRequest: MarkFirstLoginRequest,
  options?: RequestInit
): Promise<markReferralFirstLoginResponse> => {
  return customInstance<markReferralFirstLoginResponse>(getMarkReferralFirstLoginUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(markFirstLoginRequest),
  });
};

/**
 * Receives Clerk events (e.g. user.created, user.updated). Used for integration (points/referral code). Signature verification may be relaxed in early milestones.

 * @summary Clerk webhook receiver (staging)
 */
export type clerkWebhookResponse200 = {
  data: ClerkWebhook200;
  status: 200;
};

export type clerkWebhookResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type clerkWebhookResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type clerkWebhookResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type clerkWebhookResponse503 = {
  data: ServiceNotConfiguredResponse;
  status: 503;
};

export type clerkWebhookResponseSuccess = clerkWebhookResponse200 & {
  headers: Headers;
};
export type clerkWebhookResponseError = (
  | clerkWebhookResponse400
  | clerkWebhookResponse401
  | clerkWebhookResponse500
  | clerkWebhookResponse503
) & {
  headers: Headers;
};

export type clerkWebhookResponse = clerkWebhookResponseSuccess | clerkWebhookResponseError;

export const getClerkWebhookUrl = () => {
  return `/v1/auth/webhook/clerk`;
};

export const clerkWebhook = async (
  clerkWebhookBody: ClerkWebhookBody,
  options?: RequestInit
): Promise<clerkWebhookResponse> => {
  return customInstance<clerkWebhookResponse>(getClerkWebhookUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(clerkWebhookBody),
  });
};

/**
 * @summary Debug DB connectivity and counts (no secrets)
 */
export type debugDbResponse200 = {
  data: DebugDbResponse;
  status: 200;
};

export type debugDbResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type debugDbResponseSuccess = debugDbResponse200 & {
  headers: Headers;
};
export type debugDbResponseError = debugDbResponse500 & {
  headers: Headers;
};

export type debugDbResponse = debugDbResponseSuccess | debugDbResponseError;

export const getDebugDbUrl = () => {
  return `/v1/content/_debug/db`;
};

export const debugDb = async (options?: RequestInit): Promise<debugDbResponse> => {
  return customInstance<debugDbResponse>(getDebugDbUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List articles (public)
 */
export type listArticlesResponse200 = {
  data: ListArticlesResponse;
  status: 200;
};

export type listArticlesResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type listArticlesResponseSuccess = listArticlesResponse200 & {
  headers: Headers;
};
export type listArticlesResponseError = listArticlesResponse500 & {
  headers: Headers;
};

export type listArticlesResponse = listArticlesResponseSuccess | listArticlesResponseError;

export const getListArticlesUrl = (params?: ListArticlesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/content/articles?${stringifiedParams}`
    : `/v1/content/articles`;
};

export const listArticles = async (
  params?: ListArticlesParams,
  options?: RequestInit
): Promise<listArticlesResponse> => {
  return customInstance<listArticlesResponse>(getListArticlesUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get article by slug (public)
 */
export type getArticleBySlugResponse200 = {
  data: ContentArticleDto;
  status: 200;
};

export type getArticleBySlugResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getArticleBySlugResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getArticleBySlugResponseSuccess = getArticleBySlugResponse200 & {
  headers: Headers;
};
export type getArticleBySlugResponseError = (
  | getArticleBySlugResponse404
  | getArticleBySlugResponse500
) & {
  headers: Headers;
};

export type getArticleBySlugResponse =
  | getArticleBySlugResponseSuccess
  | getArticleBySlugResponseError;

export const getGetArticleBySlugUrl = (slug: string) => {
  return `/v1/content/articles/${slug}`;
};

export const getArticleBySlug = async (
  slug: string,
  options?: RequestInit
): Promise<getArticleBySlugResponse> => {
  return customInstance<getArticleBySlugResponse>(getGetArticleBySlugUrl(slug), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List blog posts (public)
 */
export type listBlogPostsResponse200 = {
  data: CursorListBlogPostsResponse;
  status: 200;
};

export type listBlogPostsResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type listBlogPostsResponseSuccess = listBlogPostsResponse200 & {
  headers: Headers;
};
export type listBlogPostsResponseError = listBlogPostsResponse500 & {
  headers: Headers;
};

export type listBlogPostsResponse = listBlogPostsResponseSuccess | listBlogPostsResponseError;

export const getListBlogPostsUrl = (params?: ListBlogPostsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/content/blog/posts?${stringifiedParams}`
    : `/v1/content/blog/posts`;
};

export const listBlogPosts = async (
  params?: ListBlogPostsParams,
  options?: RequestInit
): Promise<listBlogPostsResponse> => {
  return customInstance<listBlogPostsResponse>(getListBlogPostsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get blog post by slug (public)
 */
export type getBlogPostBySlugResponse200 = {
  data: ContentBlogPostDetailDto;
  status: 200;
};

export type getBlogPostBySlugResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getBlogPostBySlugResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getBlogPostBySlugResponseSuccess = getBlogPostBySlugResponse200 & {
  headers: Headers;
};
export type getBlogPostBySlugResponseError = (
  | getBlogPostBySlugResponse404
  | getBlogPostBySlugResponse500
) & {
  headers: Headers;
};

export type getBlogPostBySlugResponse =
  | getBlogPostBySlugResponseSuccess
  | getBlogPostBySlugResponseError;

export const getGetBlogPostBySlugUrl = (slug: string) => {
  return `/v1/content/blog/posts/${slug}`;
};

export const getBlogPostBySlug = async (
  slug: string,
  options?: RequestInit
): Promise<getBlogPostBySlugResponse> => {
  return customInstance<getBlogPostBySlugResponse>(getGetBlogPostBySlugUrl(slug), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List cities (public)
 */
export type listCitiesResponse200 = {
  data: ListCitiesResponse;
  status: 200;
};

export type listCitiesResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type listCitiesResponseSuccess = listCitiesResponse200 & {
  headers: Headers;
};
export type listCitiesResponseError = listCitiesResponse500 & {
  headers: Headers;
};

export type listCitiesResponse = listCitiesResponseSuccess | listCitiesResponseError;

export const getListCitiesUrl = (params?: ListCitiesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/content/cities?${stringifiedParams}`
    : `/v1/content/cities`;
};

export const listCities = async (
  params?: ListCitiesParams,
  options?: RequestInit
): Promise<listCitiesResponse> => {
  return customInstance<listCitiesResponse>(getListCitiesUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List city tabs (public)
 */
export type listCityTabsResponse200 = {
  data: ListContentTabsResponse;
  status: 200;
};

export type listCityTabsResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type listCityTabsResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type listCityTabsResponseSuccess = listCityTabsResponse200 & {
  headers: Headers;
};
export type listCityTabsResponseError = (listCityTabsResponse404 | listCityTabsResponse500) & {
  headers: Headers;
};

export type listCityTabsResponse = listCityTabsResponseSuccess | listCityTabsResponseError;

export const getListCityTabsUrl = (idOrSlug: string, params?: ListCityTabsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/content/cities/${idOrSlug}/tabs?${stringifiedParams}`
    : `/v1/content/cities/${idOrSlug}/tabs`;
};

export const listCityTabs = async (
  idOrSlug: string,
  params?: ListCityTabsParams,
  options?: RequestInit
): Promise<listCityTabsResponse> => {
  return customInstance<listCityTabsResponse>(getListCityTabsUrl(idOrSlug, params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List countries (public)
 */
export type listCountriesResponse200 = {
  data: ListCountriesResponse;
  status: 200;
};

export type listCountriesResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type listCountriesResponseSuccess = listCountriesResponse200 & {
  headers: Headers;
};
export type listCountriesResponseError = listCountriesResponse500 & {
  headers: Headers;
};

export type listCountriesResponse = listCountriesResponseSuccess | listCountriesResponseError;

export const getListCountriesUrl = () => {
  return `/v1/content/countries`;
};

export const listCountries = async (options?: RequestInit): Promise<listCountriesResponse> => {
  return customInstance<listCountriesResponse>(getListCountriesUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List country tabs (public)
 */
export type listCountryTabsResponse200 = {
  data: ListContentTabsResponse;
  status: 200;
};

export type listCountryTabsResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type listCountryTabsResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type listCountryTabsResponseSuccess = listCountryTabsResponse200 & {
  headers: Headers;
};
export type listCountryTabsResponseError = (
  | listCountryTabsResponse404
  | listCountryTabsResponse500
) & {
  headers: Headers;
};

export type listCountryTabsResponse = listCountryTabsResponseSuccess | listCountryTabsResponseError;

export const getListCountryTabsUrl = (idOrSlug: string, params?: ListCountryTabsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/content/countries/${idOrSlug}/tabs?${stringifiedParams}`
    : `/v1/content/countries/${idOrSlug}/tabs`;
};

export const listCountryTabs = async (
  idOrSlug: string,
  params?: ListCountryTabsParams,
  options?: RequestInit
): Promise<listCountryTabsResponse> => {
  return customInstance<listCountryTabsResponse>(getListCountryTabsUrl(idOrSlug, params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List events (public)
 */
export type listEventsResponse200 = {
  data: ListEventsResponse;
  status: 200;
};

export type listEventsResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type listEventsResponseSuccess = listEventsResponse200 & {
  headers: Headers;
};
export type listEventsResponseError = listEventsResponse500 & {
  headers: Headers;
};

export type listEventsResponse = listEventsResponseSuccess | listEventsResponseError;

export const getListEventsUrl = (params?: ListEventsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/content/events?${stringifiedParams}`
    : `/v1/content/events`;
};

export const listEvents = async (
  params?: ListEventsParams,
  options?: RequestInit
): Promise<listEventsResponse> => {
  return customInstance<listEventsResponse>(getListEventsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get event by id (public)
 */
export type getEventByIdResponse200 = {
  data: ContentEventDto;
  status: 200;
};

export type getEventByIdResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getEventByIdResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getEventByIdResponseSuccess = getEventByIdResponse200 & {
  headers: Headers;
};
export type getEventByIdResponseError = (getEventByIdResponse404 | getEventByIdResponse500) & {
  headers: Headers;
};

export type getEventByIdResponse = getEventByIdResponseSuccess | getEventByIdResponseError;

export const getGetEventByIdUrl = (id: string) => {
  return `/v1/content/events/${id}`;
};

export const getEventById = async (
  id: string,
  options?: RequestInit
): Promise<getEventByIdResponse> => {
  return customInstance<getEventByIdResponse>(getGetEventByIdUrl(id), {
    ...options,
    method: "GET",
  });
};

/**
 * Requires gateway-origin auth and asserted user context.
 * @summary Register current user for event (authorized)
 */
export type registerForEventResponse201 = {
  data: EventRegistrationResponse;
  status: 201;
};

export type registerForEventResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type registerForEventResponse409 = {
  data: ConflictResponse;
  status: 409;
};

export type registerForEventResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type registerForEventResponse503 = {
  data: ServiceAuthNotConfiguredResponse;
  status: 503;
};

export type registerForEventResponseSuccess = registerForEventResponse201 & {
  headers: Headers;
};
export type registerForEventResponseError = (
  | registerForEventResponse401
  | registerForEventResponse409
  | registerForEventResponse500
  | registerForEventResponse503
) & {
  headers: Headers;
};

export type registerForEventResponse =
  | registerForEventResponseSuccess
  | registerForEventResponseError;

export const getRegisterForEventUrl = (id: string) => {
  return `/v1/content/events/${id}/register`;
};

export const registerForEvent = async (
  id: string,
  options?: RequestInit
): Promise<registerForEventResponse> => {
  return customInstance<registerForEventResponse>(getRegisterForEventUrl(id), {
    ...options,
    method: "POST",
  });
};

/**
 * @summary List places (public)
 */
export type listPlacesResponse200 = {
  data: ListPlacesResponse;
  status: 200;
};

export type listPlacesResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type listPlacesResponseSuccess = listPlacesResponse200 & {
  headers: Headers;
};
export type listPlacesResponseError = listPlacesResponse500 & {
  headers: Headers;
};

export type listPlacesResponse = listPlacesResponseSuccess | listPlacesResponseError;

export const getListPlacesUrl = (params?: ListPlacesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/content/places?${stringifiedParams}`
    : `/v1/content/places`;
};

export const listPlaces = async (
  params?: ListPlacesParams,
  options?: RequestInit
): Promise<listPlacesResponse> => {
  return customInstance<listPlacesResponse>(getListPlacesUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get place by id or slug (public)
 */
export type getPlaceByIdOrSlugResponse200 = {
  data: ContentPlaceDto;
  status: 200;
};

export type getPlaceByIdOrSlugResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getPlaceByIdOrSlugResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getPlaceByIdOrSlugResponseSuccess = getPlaceByIdOrSlugResponse200 & {
  headers: Headers;
};
export type getPlaceByIdOrSlugResponseError = (
  | getPlaceByIdOrSlugResponse404
  | getPlaceByIdOrSlugResponse500
) & {
  headers: Headers;
};

export type getPlaceByIdOrSlugResponse =
  | getPlaceByIdOrSlugResponseSuccess
  | getPlaceByIdOrSlugResponseError;

export const getGetPlaceByIdOrSlugUrl = (idOrSlug: string) => {
  return `/v1/content/places/${idOrSlug}`;
};

export const getPlaceByIdOrSlug = async (
  idOrSlug: string,
  options?: RequestInit
): Promise<getPlaceByIdOrSlugResponse> => {
  return customInstance<getPlaceByIdOrSlugResponse>(getGetPlaceByIdOrSlugUrl(idOrSlug), {
    ...options,
    method: "GET",
  });
};

/**
 * Creates a short-lived signed token for uploading media through the canonical gateway-level media surface. Security: token issuance requires gateway-origin auth + asserted user context. Upload uses the signed token.

 * @summary Create signed upload token (authorized)
 */
export type createMediaUploadTokenResponse200 = {
  data: CreateUploadTokenResponse;
  status: 200;
};

export type createMediaUploadTokenResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type createMediaUploadTokenResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type createMediaUploadTokenResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type createMediaUploadTokenResponse503 = {
  data: ServiceAuthNotConfiguredResponse;
  status: 503;
};

export type createMediaUploadTokenResponseSuccess = createMediaUploadTokenResponse200 & {
  headers: Headers;
};
export type createMediaUploadTokenResponseError = (
  | createMediaUploadTokenResponse400
  | createMediaUploadTokenResponse401
  | createMediaUploadTokenResponse500
  | createMediaUploadTokenResponse503
) & {
  headers: Headers;
};

export type createMediaUploadTokenResponse =
  | createMediaUploadTokenResponseSuccess
  | createMediaUploadTokenResponseError;

export const getCreateMediaUploadTokenUrl = () => {
  return `/v1/media/upload-token`;
};

export const createMediaUploadToken = async (
  createUploadTokenRequest: CreateUploadTokenRequest,
  options?: RequestInit
): Promise<createMediaUploadTokenResponse> => {
  return customInstance<createMediaUploadTokenResponse>(getCreateMediaUploadTokenUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createUploadTokenRequest),
  });
};

/**
 * Uploads binary content to R2. The request is authorized by the signed token in the URL. Recommended Content-Type: image/*

 * @summary Upload media by signed token (no user auth)
 */
export type uploadMediaByTokenResponse201 = {
  data: UploadResult;
  status: 201;
};

export type uploadMediaByTokenResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type uploadMediaByTokenResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type uploadMediaByTokenResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type uploadMediaByTokenResponseSuccess = uploadMediaByTokenResponse201 & {
  headers: Headers;
};
export type uploadMediaByTokenResponseError = (
  | uploadMediaByTokenResponse400
  | uploadMediaByTokenResponse401
  | uploadMediaByTokenResponse500
) & {
  headers: Headers;
};

export type uploadMediaByTokenResponse =
  | uploadMediaByTokenResponseSuccess
  | uploadMediaByTokenResponseError;

export const getUploadMediaByTokenUrl = (token: string) => {
  return `/v1/media/upload/${token}`;
};

export const uploadMediaByToken = async (
  token: string,
  uploadMediaByTokenBody: Blob,
  options?: RequestInit
): Promise<uploadMediaByTokenResponse> => {
  return customInstance<uploadMediaByTokenResponse>(getUploadMediaByTokenUrl(token), {
    ...options,
    method: "PUT",
    headers: { "Content-Type": "application/octet-stream", ...options?.headers },
    body: JSON.stringify(uploadMediaByTokenBody),
  });
};

/**
 * Records a minimal usage binding for an existing media asset and marks it attached. Requires gateway-origin auth and media ownership.

 * @summary Attach media usage to a domain owner (authorized)
 */
export type attachMediaUsageResponse200 = {
  data: AttachMediaUsageResponse;
  status: 200;
};

export type attachMediaUsageResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type attachMediaUsageResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type attachMediaUsageResponse403 = {
  data: UnauthorizedResponse;
  status: 403;
};

export type attachMediaUsageResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type attachMediaUsageResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type attachMediaUsageResponse503 = {
  data: ServiceAuthNotConfiguredResponse;
  status: 503;
};

export type attachMediaUsageResponseSuccess = attachMediaUsageResponse200 & {
  headers: Headers;
};
export type attachMediaUsageResponseError = (
  | attachMediaUsageResponse400
  | attachMediaUsageResponse401
  | attachMediaUsageResponse403
  | attachMediaUsageResponse404
  | attachMediaUsageResponse500
  | attachMediaUsageResponse503
) & {
  headers: Headers;
};

export type attachMediaUsageResponse =
  | attachMediaUsageResponseSuccess
  | attachMediaUsageResponseError;

export const getAttachMediaUsageUrl = (mediaId: string) => {
  return `/v1/media/${mediaId}/attach`;
};

export const attachMediaUsage = async (
  mediaId: string,
  attachMediaUsageRequest: AttachMediaUsageRequest,
  options?: RequestInit
): Promise<attachMediaUsageResponse> => {
  return customInstance<attachMediaUsageResponse>(getAttachMediaUsageUrl(mediaId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(attachMediaUsageRequest),
  });
};

/**
 * User-facing read endpoint (called via gateway). Requires gateway-origin auth and asserted user context.
 * @summary Get current user points balance
 */
export type getPointsBalanceResponse200 = {
  data: UserBalance;
  status: 200;
};

export type getPointsBalanceResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getPointsBalanceResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getPointsBalanceResponse503 = {
  data: ServiceAuthNotConfiguredResponse;
  status: 503;
};

export type getPointsBalanceResponseSuccess = getPointsBalanceResponse200 & {
  headers: Headers;
};
export type getPointsBalanceResponseError = (
  | getPointsBalanceResponse401
  | getPointsBalanceResponse500
  | getPointsBalanceResponse503
) & {
  headers: Headers;
};

export type getPointsBalanceResponse =
  | getPointsBalanceResponseSuccess
  | getPointsBalanceResponseError;

export const getGetPointsBalanceUrl = () => {
  return `/v1/points/balance`;
};

export const getPointsBalance = async (
  options?: RequestInit
): Promise<getPointsBalanceResponse> => {
  return customInstance<getPointsBalanceResponse>(getGetPointsBalanceUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * User-facing read endpoint (called via gateway). Returns a paginated list of ledger transactions for the current user.
 * @summary List current user points transactions
 */
export type listPointsTransactionsResponse200 = {
  data: TransactionsPage;
  status: 200;
};

export type listPointsTransactionsResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type listPointsTransactionsResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type listPointsTransactionsResponse503 = {
  data: ServiceAuthNotConfiguredResponse;
  status: 503;
};

export type listPointsTransactionsResponseSuccess = listPointsTransactionsResponse200 & {
  headers: Headers;
};
export type listPointsTransactionsResponseError = (
  | listPointsTransactionsResponse401
  | listPointsTransactionsResponse500
  | listPointsTransactionsResponse503
) & {
  headers: Headers;
};

export type listPointsTransactionsResponse =
  | listPointsTransactionsResponseSuccess
  | listPointsTransactionsResponseError;

export const getListPointsTransactionsUrl = (params?: ListPointsTransactionsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/points/transactions?${stringifiedParams}`
    : `/v1/points/transactions`;
};

export const listPointsTransactions = async (
  params?: ListPointsTransactionsParams,
  options?: RequestInit
): Promise<listPointsTransactionsResponse> => {
  return customInstance<listPointsTransactionsResponse>(getListPointsTransactionsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary List published quests
 */
export type listQuestsResponse200 = {
  data: QuestListResponse;
  status: 200;
};

export type listQuestsResponse400 = {
  data: QuestValidationErrorResponse;
  status: 400;
};

export type listQuestsResponse500 = {
  data: QuestInternalErrorResponse;
  status: 500;
};

export type listQuestsResponseSuccess = listQuestsResponse200 & {
  headers: Headers;
};
export type listQuestsResponseError = (listQuestsResponse400 | listQuestsResponse500) & {
  headers: Headers;
};

export type listQuestsResponse = listQuestsResponseSuccess | listQuestsResponseError;

export const getListQuestsUrl = (params?: ListQuestsParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/quests?${stringifiedParams}` : `/v1/quests`;
};

export const listQuests = async (
  params?: ListQuestsParams,
  options?: RequestInit
): Promise<listQuestsResponse> => {
  return customInstance<listQuestsResponse>(getListQuestsUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create quest draft
 */
export type createQuestResponse201 = {
  data: QuestDetailResponse;
  status: 201;
};

export type createQuestResponse400 = {
  data: QuestValidationErrorResponse;
  status: 400;
};

export type createQuestResponse401 = {
  data: QuestUnauthorizedResponse;
  status: 401;
};

export type createQuestResponse403 = {
  data: QuestForbiddenResponse;
  status: 403;
};

export type createQuestResponse500 = {
  data: QuestInternalErrorResponse;
  status: 500;
};

export type createQuestResponse503 = {
  data: QuestServiceAuthNotConfiguredResponse;
  status: 503;
};

export type createQuestResponseSuccess = createQuestResponse201 & {
  headers: Headers;
};
export type createQuestResponseError = (
  | createQuestResponse400
  | createQuestResponse401
  | createQuestResponse403
  | createQuestResponse500
  | createQuestResponse503
) & {
  headers: Headers;
};

export type createQuestResponse = createQuestResponseSuccess | createQuestResponseError;

export const getCreateQuestUrl = () => {
  return `/v1/quests`;
};

export const createQuest = async (
  createQuestRequest: CreateQuestRequest,
  options?: RequestInit
): Promise<createQuestResponse> => {
  return customInstance<createQuestResponse>(getCreateQuestUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createQuestRequest),
  });
};

/**
 * @summary Get published quest details
 */
export type getQuestResponse200 = {
  data: QuestDetailResponse;
  status: 200;
};

export type getQuestResponse404 = {
  data: QuestNotFoundResponse;
  status: 404;
};

export type getQuestResponse500 = {
  data: QuestInternalErrorResponse;
  status: 500;
};

export type getQuestResponseSuccess = getQuestResponse200 & {
  headers: Headers;
};
export type getQuestResponseError = (getQuestResponse404 | getQuestResponse500) & {
  headers: Headers;
};

export type getQuestResponse = getQuestResponseSuccess | getQuestResponseError;

export const getGetQuestUrl = (questId: string) => {
  return `/v1/quests/${questId}`;
};

export const getQuest = async (
  questId: string,
  options?: RequestInit
): Promise<getQuestResponse> => {
  return customInstance<getQuestResponse>(getGetQuestUrl(questId), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get current user progress for a quest
 */
export type getQuestProgressResponse200 = {
  data: QuestProgressResponse;
  status: 200;
};

export type getQuestProgressResponse401 = {
  data: QuestUnauthorizedResponse;
  status: 401;
};

export type getQuestProgressResponse404 = {
  data: QuestNotFoundResponse;
  status: 404;
};

export type getQuestProgressResponse500 = {
  data: QuestInternalErrorResponse;
  status: 500;
};

export type getQuestProgressResponse503 = {
  data: QuestServiceAuthNotConfiguredResponse;
  status: 503;
};

export type getQuestProgressResponseSuccess = getQuestProgressResponse200 & {
  headers: Headers;
};
export type getQuestProgressResponseError = (
  | getQuestProgressResponse401
  | getQuestProgressResponse404
  | getQuestProgressResponse500
  | getQuestProgressResponse503
) & {
  headers: Headers;
};

export type getQuestProgressResponse =
  | getQuestProgressResponseSuccess
  | getQuestProgressResponseError;

export const getGetQuestProgressUrl = (questId: string) => {
  return `/v1/quests/${questId}/progress`;
};

export const getQuestProgress = async (
  questId: string,
  options?: RequestInit
): Promise<getQuestProgressResponse> => {
  return customInstance<getQuestProgressResponse>(getGetQuestProgressUrl(questId), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Publish quest
 */
export type publishQuestResponse200 = {
  data: QuestDetailResponse;
  status: 200;
};

export type publishQuestResponse401 = {
  data: QuestUnauthorizedResponse;
  status: 401;
};

export type publishQuestResponse403 = {
  data: QuestForbiddenResponse;
  status: 403;
};

export type publishQuestResponse404 = {
  data: QuestNotFoundResponse;
  status: 404;
};

export type publishQuestResponse409 = {
  data: QuestConflictResponse;
  status: 409;
};

export type publishQuestResponse500 = {
  data: QuestInternalErrorResponse;
  status: 500;
};

export type publishQuestResponse503 = {
  data: QuestServiceAuthNotConfiguredResponse;
  status: 503;
};

export type publishQuestResponseSuccess = publishQuestResponse200 & {
  headers: Headers;
};
export type publishQuestResponseError = (
  | publishQuestResponse401
  | publishQuestResponse403
  | publishQuestResponse404
  | publishQuestResponse409
  | publishQuestResponse500
  | publishQuestResponse503
) & {
  headers: Headers;
};

export type publishQuestResponse = publishQuestResponseSuccess | publishQuestResponseError;

export const getPublishQuestUrl = (questId: string) => {
  return `/v1/quests/${questId}/publish`;
};

export const publishQuest = async (
  questId: string,
  options?: RequestInit
): Promise<publishQuestResponse> => {
  return customInstance<publishQuestResponse>(getPublishQuestUrl(questId), {
    ...options,
    method: "POST",
  });
};

/**
 * @summary Start quest for current user
 */
export type startQuestResponse200 = {
  data: QuestProgressResponse;
  status: 200;
};

export type startQuestResponse401 = {
  data: QuestUnauthorizedResponse;
  status: 401;
};

export type startQuestResponse404 = {
  data: QuestNotFoundResponse;
  status: 404;
};

export type startQuestResponse409 = {
  data: QuestConflictResponse;
  status: 409;
};

export type startQuestResponse500 = {
  data: QuestInternalErrorResponse;
  status: 500;
};

export type startQuestResponse503 = {
  data: QuestServiceAuthNotConfiguredResponse;
  status: 503;
};

export type startQuestResponseSuccess = startQuestResponse200 & {
  headers: Headers;
};
export type startQuestResponseError = (
  | startQuestResponse401
  | startQuestResponse404
  | startQuestResponse409
  | startQuestResponse500
  | startQuestResponse503
) & {
  headers: Headers;
};

export type startQuestResponse = startQuestResponseSuccess | startQuestResponseError;

export const getStartQuestUrl = (questId: string) => {
  return `/v1/quests/${questId}/start`;
};

export const startQuest = async (
  questId: string,
  options?: RequestInit
): Promise<startQuestResponse> => {
  return customInstance<startQuestResponse>(getStartQuestUrl(questId), {
    ...options,
    method: "POST",
  });
};

/**
 * @summary Add step to draft quest
 */
export type addQuestStepResponse201 = {
  data: QuestStepResponse;
  status: 201;
};

export type addQuestStepResponse400 = {
  data: QuestValidationErrorResponse;
  status: 400;
};

export type addQuestStepResponse401 = {
  data: QuestUnauthorizedResponse;
  status: 401;
};

export type addQuestStepResponse403 = {
  data: QuestForbiddenResponse;
  status: 403;
};

export type addQuestStepResponse404 = {
  data: QuestNotFoundResponse;
  status: 404;
};

export type addQuestStepResponse409 = {
  data: QuestConflictResponse;
  status: 409;
};

export type addQuestStepResponse500 = {
  data: QuestInternalErrorResponse;
  status: 500;
};

export type addQuestStepResponse503 = {
  data: QuestServiceAuthNotConfiguredResponse;
  status: 503;
};

export type addQuestStepResponseSuccess = addQuestStepResponse201 & {
  headers: Headers;
};
export type addQuestStepResponseError = (
  | addQuestStepResponse400
  | addQuestStepResponse401
  | addQuestStepResponse403
  | addQuestStepResponse404
  | addQuestStepResponse409
  | addQuestStepResponse500
  | addQuestStepResponse503
) & {
  headers: Headers;
};

export type addQuestStepResponse = addQuestStepResponseSuccess | addQuestStepResponseError;

export const getAddQuestStepUrl = (questId: string) => {
  return `/v1/quests/${questId}/steps`;
};

export const addQuestStep = async (
  questId: string,
  addQuestStepRequest: AddQuestStepRequest,
  options?: RequestInit
): Promise<addQuestStepResponse> => {
  return customInstance<addQuestStepResponse>(getAddQuestStepUrl(questId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(addQuestStepRequest),
  });
};

/**
 * @summary Submit proof for the current quest step
 */
export type submitQuestStepResponse201 = {
  data: QuestSubmissionResponse;
  status: 201;
};

export type submitQuestStepResponse400 = {
  data: QuestValidationErrorResponse;
  status: 400;
};

export type submitQuestStepResponse401 = {
  data: QuestUnauthorizedResponse;
  status: 401;
};

export type submitQuestStepResponse404 = {
  data: QuestNotFoundResponse;
  status: 404;
};

export type submitQuestStepResponse409 = {
  data: QuestConflictResponse;
  status: 409;
};

export type submitQuestStepResponse500 = {
  data: QuestInternalErrorResponse;
  status: 500;
};

export type submitQuestStepResponse503 = {
  data: QuestServiceAuthNotConfiguredResponse;
  status: 503;
};

export type submitQuestStepResponseSuccess = submitQuestStepResponse201 & {
  headers: Headers;
};
export type submitQuestStepResponseError = (
  | submitQuestStepResponse400
  | submitQuestStepResponse401
  | submitQuestStepResponse404
  | submitQuestStepResponse409
  | submitQuestStepResponse500
  | submitQuestStepResponse503
) & {
  headers: Headers;
};

export type submitQuestStepResponse = submitQuestStepResponseSuccess | submitQuestStepResponseError;

export const getSubmitQuestStepUrl = (questId: string, stepId: string) => {
  return `/v1/quests/${questId}/steps/${stepId}/submit`;
};

export const submitQuestStep = async (
  questId: string,
  stepId: string,
  submitQuestStepRequest: SubmitQuestStepRequest,
  options?: RequestInit
): Promise<submitQuestStepResponse> => {
  return customInstance<submitQuestStepResponse>(getSubmitQuestStepUrl(questId, stepId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(submitQuestStepRequest),
  });
};

/**
 * @summary List submissions for quest review
 */
export type listQuestSubmissionsResponse200 = {
  data: QuestSubmissionListResponse;
  status: 200;
};

export type listQuestSubmissionsResponse401 = {
  data: QuestUnauthorizedResponse;
  status: 401;
};

export type listQuestSubmissionsResponse403 = {
  data: QuestForbiddenResponse;
  status: 403;
};

export type listQuestSubmissionsResponse404 = {
  data: QuestNotFoundResponse;
  status: 404;
};

export type listQuestSubmissionsResponse500 = {
  data: QuestInternalErrorResponse;
  status: 500;
};

export type listQuestSubmissionsResponse503 = {
  data: QuestServiceAuthNotConfiguredResponse;
  status: 503;
};

export type listQuestSubmissionsResponseSuccess = listQuestSubmissionsResponse200 & {
  headers: Headers;
};
export type listQuestSubmissionsResponseError = (
  | listQuestSubmissionsResponse401
  | listQuestSubmissionsResponse403
  | listQuestSubmissionsResponse404
  | listQuestSubmissionsResponse500
  | listQuestSubmissionsResponse503
) & {
  headers: Headers;
};

export type listQuestSubmissionsResponse =
  | listQuestSubmissionsResponseSuccess
  | listQuestSubmissionsResponseError;

export const getListQuestSubmissionsUrl = (
  questId: string,
  params?: ListQuestSubmissionsParams
) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/quests/${questId}/submissions?${stringifiedParams}`
    : `/v1/quests/${questId}/submissions`;
};

export const listQuestSubmissions = async (
  questId: string,
  params?: ListQuestSubmissionsParams,
  options?: RequestInit
): Promise<listQuestSubmissionsResponse> => {
  return customInstance<listQuestSubmissionsResponse>(getListQuestSubmissionsUrl(questId, params), {
    ...options,
    method: "GET",
  });
};

/**
 * User-facing write endpoint (called via gateway). Links current user as referee to referrer resolved by referral code. Invariant: referee can have at most one referrer.

 * @summary Claim referral code for current user (idempotent)
 */
export type claimReferralResponse200 = {
  data: ClaimReferralResponse;
  status: 200;
};

export type claimReferralResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type claimReferralResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type claimReferralResponse409 = {
  data: ConflictResponse;
  status: 409;
};

export type claimReferralResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type claimReferralResponse503 = {
  data: ServiceAuthNotConfiguredResponse;
  status: 503;
};

export type claimReferralResponseSuccess = claimReferralResponse200 & {
  headers: Headers;
};
export type claimReferralResponseError = (
  | claimReferralResponse401
  | claimReferralResponse404
  | claimReferralResponse409
  | claimReferralResponse500
  | claimReferralResponse503
) & {
  headers: Headers;
};

export type claimReferralResponse = claimReferralResponseSuccess | claimReferralResponseError;

export const getClaimReferralUrl = () => {
  return `/v1/referral/claim`;
};

export const claimReferral = async (
  claimReferralRequest: ClaimReferralRequest,
  options?: RequestInit
): Promise<claimReferralResponse> => {
  return customInstance<claimReferralResponse>(getClaimReferralUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(claimReferralRequest),
  });
};

/**
 * M3 behavior: may lazily create referral code if missing (idempotent upsert).

 * @summary Get current user's referral code
 */
export type getReferralCodeResponse200 = {
  data: ReferralCodeResponse;
  status: 200;
};

export type getReferralCodeResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getReferralCodeResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getReferralCodeResponse503 = {
  data: ServiceAuthNotConfiguredResponse;
  status: 503;
};

export type getReferralCodeResponseSuccess = getReferralCodeResponse200 & {
  headers: Headers;
};
export type getReferralCodeResponseError = (
  | getReferralCodeResponse401
  | getReferralCodeResponse500
  | getReferralCodeResponse503
) & {
  headers: Headers;
};

export type getReferralCodeResponse = getReferralCodeResponseSuccess | getReferralCodeResponseError;

export const getGetReferralCodeUrl = () => {
  return `/v1/referral/code`;
};

export const getReferralCode = async (options?: RequestInit): Promise<getReferralCodeResponse> => {
  return customInstance<getReferralCodeResponse>(getGetReferralCodeUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * User-facing read endpoint (called via gateway). Returns minimal referral statistics for the current user (M3 scope).
 * @summary Get current user's referral stats
 */
export type getReferralStatsResponse200 = {
  data: ReferralStatsResponse;
  status: 200;
};

export type getReferralStatsResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getReferralStatsResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getReferralStatsResponse503 = {
  data: ServiceAuthNotConfiguredResponse;
  status: 503;
};

export type getReferralStatsResponseSuccess = getReferralStatsResponse200 & {
  headers: Headers;
};
export type getReferralStatsResponseError = (
  | getReferralStatsResponse401
  | getReferralStatsResponse500
  | getReferralStatsResponse503
) & {
  headers: Headers;
};

export type getReferralStatsResponse =
  | getReferralStatsResponseSuccess
  | getReferralStatsResponseError;

export const getGetReferralStatsUrl = () => {
  return `/v1/referral/stats`;
};

export const getReferralStats = async (
  options?: RequestInit
): Promise<getReferralStatsResponse> => {
  return customInstance<getReferralStatsResponse>(getGetReferralStatsUrl(), {
    ...options,
    method: "GET",
  });
};

/**
 * User-facing read endpoint (called via gateway). Returns a two-level referral tree (M4 UI needs). Note: user profile details are not part of Referral Service in M3; only userIds and timestamps are returned.

 * @summary Get current user's referral tree (depth 1..2)
 */
export type getReferralTreeResponse200 = {
  data: ReferralTreeResponse;
  status: 200;
};

export type getReferralTreeResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getReferralTreeResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getReferralTreeResponse503 = {
  data: ServiceAuthNotConfiguredResponse;
  status: 503;
};

export type getReferralTreeResponseSuccess = getReferralTreeResponse200 & {
  headers: Headers;
};
export type getReferralTreeResponseError = (
  | getReferralTreeResponse401
  | getReferralTreeResponse500
  | getReferralTreeResponse503
) & {
  headers: Headers;
};

export type getReferralTreeResponse = getReferralTreeResponseSuccess | getReferralTreeResponseError;

export const getGetReferralTreeUrl = (params?: GetReferralTreeParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/referral/tree?${stringifiedParams}`
    : `/v1/referral/tree`;
};

export const getReferralTree = async (
  params?: GetReferralTreeParams,
  options?: RequestInit
): Promise<getReferralTreeResponse> => {
  return customInstance<getReferralTreeResponse>(getGetReferralTreeUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get activity feed
 */
export type getSpaceActivityFeedResponse200 = {
  data: SpaceActivityFeedResponse;
  status: 200;
};

export type getSpaceActivityFeedResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getSpaceActivityFeedResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getSpaceActivityFeedResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type getSpaceActivityFeedResponseSuccess = getSpaceActivityFeedResponse200 & {
  headers: Headers;
};
export type getSpaceActivityFeedResponseError = (
  | getSpaceActivityFeedResponse401
  | getSpaceActivityFeedResponse500
  | getSpaceActivityFeedResponse503
) & {
  headers: Headers;
};

export type getSpaceActivityFeedResponse =
  | getSpaceActivityFeedResponseSuccess
  | getSpaceActivityFeedResponseError;

export const getGetSpaceActivityFeedUrl = (params?: GetSpaceActivityFeedParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/space/feed/activity?${stringifiedParams}`
    : `/v1/space/feed/activity`;
};

export const getSpaceActivityFeed = async (
  params?: GetSpaceActivityFeedParams,
  options?: RequestInit
): Promise<getSpaceActivityFeedResponse> => {
  return customInstance<getSpaceActivityFeedResponse>(getGetSpaceActivityFeedUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get group feed
 */
export type getSpaceGroupFeedResponse200 = {
  data: SpaceFeedResponse;
  status: 200;
};

export type getSpaceGroupFeedResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getSpaceGroupFeedResponse403 = {
  data: SpaceForbiddenResponse;
  status: 403;
};

export type getSpaceGroupFeedResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getSpaceGroupFeedResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getSpaceGroupFeedResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type getSpaceGroupFeedResponseSuccess = getSpaceGroupFeedResponse200 & {
  headers: Headers;
};
export type getSpaceGroupFeedResponseError = (
  | getSpaceGroupFeedResponse401
  | getSpaceGroupFeedResponse403
  | getSpaceGroupFeedResponse404
  | getSpaceGroupFeedResponse500
  | getSpaceGroupFeedResponse503
) & {
  headers: Headers;
};

export type getSpaceGroupFeedResponse =
  | getSpaceGroupFeedResponseSuccess
  | getSpaceGroupFeedResponseError;

export const getGetSpaceGroupFeedUrl = (groupId: string, params?: GetSpaceGroupFeedParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/space/feed/group/${groupId}?${stringifiedParams}`
    : `/v1/space/feed/group/${groupId}`;
};

export const getSpaceGroupFeed = async (
  groupId: string,
  params?: GetSpaceGroupFeedParams,
  options?: RequestInit
): Promise<getSpaceGroupFeedResponse> => {
  return customInstance<getSpaceGroupFeedResponse>(getGetSpaceGroupFeedUrl(groupId, params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get home feed
 */
export type getSpaceHomeFeedResponse200 = {
  data: SpaceFeedResponse;
  status: 200;
};

export type getSpaceHomeFeedResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getSpaceHomeFeedResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getSpaceHomeFeedResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type getSpaceHomeFeedResponseSuccess = getSpaceHomeFeedResponse200 & {
  headers: Headers;
};
export type getSpaceHomeFeedResponseError = (
  | getSpaceHomeFeedResponse401
  | getSpaceHomeFeedResponse500
  | getSpaceHomeFeedResponse503
) & {
  headers: Headers;
};

export type getSpaceHomeFeedResponse =
  | getSpaceHomeFeedResponseSuccess
  | getSpaceHomeFeedResponseError;

export const getGetSpaceHomeFeedUrl = (params?: GetSpaceHomeFeedParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/space/feed/home?${stringifiedParams}`
    : `/v1/space/feed/home`;
};

export const getSpaceHomeFeed = async (
  params?: GetSpaceHomeFeedParams,
  options?: RequestInit
): Promise<getSpaceHomeFeedResponse> => {
  return customInstance<getSpaceHomeFeedResponse>(getGetSpaceHomeFeedUrl(params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Get profile feed
 */
export type getSpaceProfileFeedResponse200 = {
  data: SpaceFeedResponse;
  status: 200;
};

export type getSpaceProfileFeedResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getSpaceProfileFeedResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getSpaceProfileFeedResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type getSpaceProfileFeedResponseSuccess = getSpaceProfileFeedResponse200 & {
  headers: Headers;
};
export type getSpaceProfileFeedResponseError = (
  | getSpaceProfileFeedResponse401
  | getSpaceProfileFeedResponse500
  | getSpaceProfileFeedResponse503
) & {
  headers: Headers;
};

export type getSpaceProfileFeedResponse =
  | getSpaceProfileFeedResponseSuccess
  | getSpaceProfileFeedResponseError;

export const getGetSpaceProfileFeedUrl = (userId: string, params?: GetSpaceProfileFeedParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? "null" : value.toString());
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/space/feed/profile/${userId}?${stringifiedParams}`
    : `/v1/space/feed/profile/${userId}`;
};

export const getSpaceProfileFeed = async (
  userId: string,
  params?: GetSpaceProfileFeedParams,
  options?: RequestInit
): Promise<getSpaceProfileFeedResponse> => {
  return customInstance<getSpaceProfileFeedResponse>(getGetSpaceProfileFeedUrl(userId, params), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Create group
 */
export type createSpaceGroupResponse201 = {
  data: SpaceGroupResponse;
  status: 201;
};

export type createSpaceGroupResponse400 = {
  data: SpaceValidationErrorResponse;
  status: 400;
};

export type createSpaceGroupResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type createSpaceGroupResponse409 = {
  data: ConflictResponse;
  status: 409;
};

export type createSpaceGroupResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type createSpaceGroupResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type createSpaceGroupResponseSuccess = createSpaceGroupResponse201 & {
  headers: Headers;
};
export type createSpaceGroupResponseError = (
  | createSpaceGroupResponse400
  | createSpaceGroupResponse401
  | createSpaceGroupResponse409
  | createSpaceGroupResponse500
  | createSpaceGroupResponse503
) & {
  headers: Headers;
};

export type createSpaceGroupResponse =
  | createSpaceGroupResponseSuccess
  | createSpaceGroupResponseError;

export const getCreateSpaceGroupUrl = () => {
  return `/v1/space/groups`;
};

export const createSpaceGroup = async (
  createSpaceGroupRequest: CreateSpaceGroupRequest,
  options?: RequestInit
): Promise<createSpaceGroupResponse> => {
  return customInstance<createSpaceGroupResponse>(getCreateSpaceGroupUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createSpaceGroupRequest),
  });
};

/**
 * @summary Get group by id
 */
export type getSpaceGroupResponse200 = {
  data: SpaceGroupResponse;
  status: 200;
};

export type getSpaceGroupResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getSpaceGroupResponse403 = {
  data: SpaceForbiddenResponse;
  status: 403;
};

export type getSpaceGroupResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getSpaceGroupResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getSpaceGroupResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type getSpaceGroupResponseSuccess = getSpaceGroupResponse200 & {
  headers: Headers;
};
export type getSpaceGroupResponseError = (
  | getSpaceGroupResponse401
  | getSpaceGroupResponse403
  | getSpaceGroupResponse404
  | getSpaceGroupResponse500
  | getSpaceGroupResponse503
) & {
  headers: Headers;
};

export type getSpaceGroupResponse = getSpaceGroupResponseSuccess | getSpaceGroupResponseError;

export const getGetSpaceGroupUrl = (groupId: string) => {
  return `/v1/space/groups/${groupId}`;
};

export const getSpaceGroup = async (
  groupId: string,
  options?: RequestInit
): Promise<getSpaceGroupResponse> => {
  return customInstance<getSpaceGroupResponse>(getGetSpaceGroupUrl(groupId), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Join group
 */
export type joinSpaceGroupResponse200 = {
  data: SpaceGroupMembershipResponse;
  status: 200;
};

export type joinSpaceGroupResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type joinSpaceGroupResponse403 = {
  data: SpaceForbiddenResponse;
  status: 403;
};

export type joinSpaceGroupResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type joinSpaceGroupResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type joinSpaceGroupResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type joinSpaceGroupResponseSuccess = joinSpaceGroupResponse200 & {
  headers: Headers;
};
export type joinSpaceGroupResponseError = (
  | joinSpaceGroupResponse401
  | joinSpaceGroupResponse403
  | joinSpaceGroupResponse404
  | joinSpaceGroupResponse500
  | joinSpaceGroupResponse503
) & {
  headers: Headers;
};

export type joinSpaceGroupResponse = joinSpaceGroupResponseSuccess | joinSpaceGroupResponseError;

export const getJoinSpaceGroupUrl = (groupId: string) => {
  return `/v1/space/groups/${groupId}/join`;
};

export const joinSpaceGroup = async (
  groupId: string,
  options?: RequestInit
): Promise<joinSpaceGroupResponse> => {
  return customInstance<joinSpaceGroupResponse>(getJoinSpaceGroupUrl(groupId), {
    ...options,
    method: "POST",
  });
};

/**
 * @summary Leave group
 */
export type leaveSpaceGroupResponse204 = {
  data: void;
  status: 204;
};

export type leaveSpaceGroupResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type leaveSpaceGroupResponse403 = {
  data: SpaceForbiddenResponse;
  status: 403;
};

export type leaveSpaceGroupResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type leaveSpaceGroupResponse409 = {
  data: ConflictResponse;
  status: 409;
};

export type leaveSpaceGroupResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type leaveSpaceGroupResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type leaveSpaceGroupResponseSuccess = leaveSpaceGroupResponse204 & {
  headers: Headers;
};
export type leaveSpaceGroupResponseError = (
  | leaveSpaceGroupResponse401
  | leaveSpaceGroupResponse403
  | leaveSpaceGroupResponse404
  | leaveSpaceGroupResponse409
  | leaveSpaceGroupResponse500
  | leaveSpaceGroupResponse503
) & {
  headers: Headers;
};

export type leaveSpaceGroupResponse = leaveSpaceGroupResponseSuccess | leaveSpaceGroupResponseError;

export const getLeaveSpaceGroupUrl = (groupId: string) => {
  return `/v1/space/groups/${groupId}/leave`;
};

export const leaveSpaceGroup = async (
  groupId: string,
  options?: RequestInit
): Promise<leaveSpaceGroupResponse> => {
  return customInstance<leaveSpaceGroupResponse>(getLeaveSpaceGroupUrl(groupId), {
    ...options,
    method: "POST",
  });
};

/**
 * @summary Create post or repost
 */
export type createSpacePostResponse201 = {
  data: SpacePostResponse;
  status: 201;
};

export type createSpacePostResponse400 = {
  data: SpaceValidationErrorResponse;
  status: 400;
};

export type createSpacePostResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type createSpacePostResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type createSpacePostResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type createSpacePostResponseSuccess = createSpacePostResponse201 & {
  headers: Headers;
};
export type createSpacePostResponseError = (
  | createSpacePostResponse400
  | createSpacePostResponse401
  | createSpacePostResponse500
  | createSpacePostResponse503
) & {
  headers: Headers;
};

export type createSpacePostResponse = createSpacePostResponseSuccess | createSpacePostResponseError;

export const getCreateSpacePostUrl = () => {
  return `/v1/space/posts`;
};

export const createSpacePost = async (
  createSpacePostRequest: CreateSpacePostRequest,
  options?: RequestInit
): Promise<createSpacePostResponse> => {
  return customInstance<createSpacePostResponse>(getCreateSpacePostUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createSpacePostRequest),
  });
};

/**
 * @summary Soft-delete post
 */
export type deleteSpacePostResponse204 = {
  data: void;
  status: 204;
};

export type deleteSpacePostResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type deleteSpacePostResponse403 = {
  data: SpaceForbiddenResponse;
  status: 403;
};

export type deleteSpacePostResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type deleteSpacePostResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type deleteSpacePostResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type deleteSpacePostResponseSuccess = deleteSpacePostResponse204 & {
  headers: Headers;
};
export type deleteSpacePostResponseError = (
  | deleteSpacePostResponse401
  | deleteSpacePostResponse403
  | deleteSpacePostResponse404
  | deleteSpacePostResponse500
  | deleteSpacePostResponse503
) & {
  headers: Headers;
};

export type deleteSpacePostResponse = deleteSpacePostResponseSuccess | deleteSpacePostResponseError;

export const getDeleteSpacePostUrl = (postId: string) => {
  return `/v1/space/posts/${postId}`;
};

export const deleteSpacePost = async (
  postId: string,
  options?: RequestInit
): Promise<deleteSpacePostResponse> => {
  return customInstance<deleteSpacePostResponse>(getDeleteSpacePostUrl(postId), {
    ...options,
    method: "DELETE",
  });
};

/**
 * @summary Get post by id
 */
export type getSpacePostResponse200 = {
  data: SpacePostResponse;
  status: 200;
};

export type getSpacePostResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getSpacePostResponse403 = {
  data: SpaceForbiddenResponse;
  status: 403;
};

export type getSpacePostResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getSpacePostResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getSpacePostResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type getSpacePostResponseSuccess = getSpacePostResponse200 & {
  headers: Headers;
};
export type getSpacePostResponseError = (
  | getSpacePostResponse401
  | getSpacePostResponse403
  | getSpacePostResponse404
  | getSpacePostResponse500
  | getSpacePostResponse503
) & {
  headers: Headers;
};

export type getSpacePostResponse = getSpacePostResponseSuccess | getSpacePostResponseError;

export const getGetSpacePostUrl = (postId: string) => {
  return `/v1/space/posts/${postId}`;
};

export const getSpacePost = async (
  postId: string,
  options?: RequestInit
): Promise<getSpacePostResponse> => {
  return customInstance<getSpacePostResponse>(getGetSpacePostUrl(postId), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Attach media relation to post
 */
export type attachSpacePostMediaResponse200 = {
  data: SpacePostMediaAttachmentResponse;
  status: 200;
};

export type attachSpacePostMediaResponse400 = {
  data: SpaceValidationErrorResponse;
  status: 400;
};

export type attachSpacePostMediaResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type attachSpacePostMediaResponse403 = {
  data: SpaceForbiddenResponse;
  status: 403;
};

export type attachSpacePostMediaResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type attachSpacePostMediaResponse429 = {
  data: SpaceRateLimitedResponse;
  status: 429;
};

export type attachSpacePostMediaResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type attachSpacePostMediaResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type attachSpacePostMediaResponseSuccess = attachSpacePostMediaResponse200 & {
  headers: Headers;
};
export type attachSpacePostMediaResponseError = (
  | attachSpacePostMediaResponse400
  | attachSpacePostMediaResponse401
  | attachSpacePostMediaResponse403
  | attachSpacePostMediaResponse404
  | attachSpacePostMediaResponse429
  | attachSpacePostMediaResponse500
  | attachSpacePostMediaResponse503
) & {
  headers: Headers;
};

export type attachSpacePostMediaResponse =
  | attachSpacePostMediaResponseSuccess
  | attachSpacePostMediaResponseError;

export const getAttachSpacePostMediaUrl = (postId: string) => {
  return `/v1/space/posts/${postId}/media`;
};

export const attachSpacePostMedia = async (
  postId: string,
  attachSpacePostMediaRequest: AttachSpacePostMediaRequest,
  options?: RequestInit
): Promise<attachSpacePostMediaResponse> => {
  return customInstance<attachSpacePostMediaResponse>(getAttachSpacePostMediaUrl(postId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(attachSpacePostMediaRequest),
  });
};

/**
 * @summary Remove media relation from post
 */
export type detachSpacePostMediaResponse204 = {
  data: void;
  status: 204;
};

export type detachSpacePostMediaResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type detachSpacePostMediaResponse403 = {
  data: SpaceForbiddenResponse;
  status: 403;
};

export type detachSpacePostMediaResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type detachSpacePostMediaResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type detachSpacePostMediaResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type detachSpacePostMediaResponseSuccess = detachSpacePostMediaResponse204 & {
  headers: Headers;
};
export type detachSpacePostMediaResponseError = (
  | detachSpacePostMediaResponse401
  | detachSpacePostMediaResponse403
  | detachSpacePostMediaResponse404
  | detachSpacePostMediaResponse500
  | detachSpacePostMediaResponse503
) & {
  headers: Headers;
};

export type detachSpacePostMediaResponse =
  | detachSpacePostMediaResponseSuccess
  | detachSpacePostMediaResponseError;

export const getDetachSpacePostMediaUrl = (postId: string, mediaId: string) => {
  return `/v1/space/posts/${postId}/media/${mediaId}`;
};

export const detachSpacePostMedia = async (
  postId: string,
  mediaId: string,
  options?: RequestInit
): Promise<detachSpacePostMediaResponse> => {
  return customInstance<detachSpacePostMediaResponse>(getDetachSpacePostMediaUrl(postId, mediaId), {
    ...options,
    method: "DELETE",
  });
};

/**
 * @summary Convenience repost of an existing Space post
 */
export type repostSpacePostResponse201 = {
  data: SpacePostResponse;
  status: 201;
};

export type repostSpacePostResponse400 = {
  data: SpaceValidationErrorResponse;
  status: 400;
};

export type repostSpacePostResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type repostSpacePostResponse403 = {
  data: SpaceForbiddenResponse;
  status: 403;
};

export type repostSpacePostResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type repostSpacePostResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type repostSpacePostResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type repostSpacePostResponseSuccess = repostSpacePostResponse201 & {
  headers: Headers;
};
export type repostSpacePostResponseError = (
  | repostSpacePostResponse400
  | repostSpacePostResponse401
  | repostSpacePostResponse403
  | repostSpacePostResponse404
  | repostSpacePostResponse500
  | repostSpacePostResponse503
) & {
  headers: Headers;
};

export type repostSpacePostResponse = repostSpacePostResponseSuccess | repostSpacePostResponseError;

export const getRepostSpacePostUrl = (postId: string) => {
  return `/v1/space/posts/${postId}/repost`;
};

export const repostSpacePost = async (
  postId: string,
  createSpaceRepostRequest?: CreateSpaceRepostRequest,
  options?: RequestInit
): Promise<repostSpacePostResponse> => {
  return customInstance<repostSpacePostResponse>(getRepostSpacePostUrl(postId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(createSpaceRepostRequest),
  });
};

/**
 * @summary Get social profile projection
 */
export type getSpaceProfileResponse200 = {
  data: SpaceProfileResponse;
  status: 200;
};

export type getSpaceProfileResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type getSpaceProfileResponse404 = {
  data: NotFoundResponse;
  status: 404;
};

export type getSpaceProfileResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type getSpaceProfileResponse503 = {
  data: SpaceServiceAuthNotConfiguredResponse;
  status: 503;
};

export type getSpaceProfileResponseSuccess = getSpaceProfileResponse200 & {
  headers: Headers;
};
export type getSpaceProfileResponseError = (
  | getSpaceProfileResponse401
  | getSpaceProfileResponse404
  | getSpaceProfileResponse500
  | getSpaceProfileResponse503
) & {
  headers: Headers;
};

export type getSpaceProfileResponse = getSpaceProfileResponseSuccess | getSpaceProfileResponseError;

export const getGetSpaceProfileUrl = (userId: string) => {
  return `/v1/space/profiles/${userId}`;
};

export const getSpaceProfile = async (
  userId: string,
  options?: RequestInit
): Promise<getSpaceProfileResponse> => {
  return customInstance<getSpaceProfileResponse>(getGetSpaceProfileUrl(userId), {
    ...options,
    method: "GET",
  });
};

/**
 * @summary Approve or reject submission
 */
export type reviewQuestSubmissionResponse200 = {
  data: QuestSubmissionResponse;
  status: 200;
};

export type reviewQuestSubmissionResponse400 = {
  data: QuestValidationErrorResponse;
  status: 400;
};

export type reviewQuestSubmissionResponse401 = {
  data: QuestUnauthorizedResponse;
  status: 401;
};

export type reviewQuestSubmissionResponse403 = {
  data: QuestForbiddenResponse;
  status: 403;
};

export type reviewQuestSubmissionResponse404 = {
  data: QuestNotFoundResponse;
  status: 404;
};

export type reviewQuestSubmissionResponse409 = {
  data: QuestConflictResponse;
  status: 409;
};

export type reviewQuestSubmissionResponse500 = {
  data: QuestInternalErrorResponse;
  status: 500;
};

export type reviewQuestSubmissionResponse503 = {
  data: QuestServiceAuthNotConfiguredResponse;
  status: 503;
};

export type reviewQuestSubmissionResponseSuccess = reviewQuestSubmissionResponse200 & {
  headers: Headers;
};
export type reviewQuestSubmissionResponseError = (
  | reviewQuestSubmissionResponse400
  | reviewQuestSubmissionResponse401
  | reviewQuestSubmissionResponse403
  | reviewQuestSubmissionResponse404
  | reviewQuestSubmissionResponse409
  | reviewQuestSubmissionResponse500
  | reviewQuestSubmissionResponse503
) & {
  headers: Headers;
};

export type reviewQuestSubmissionResponse =
  | reviewQuestSubmissionResponseSuccess
  | reviewQuestSubmissionResponseError;

export const getReviewQuestSubmissionUrl = (submissionId: string) => {
  return `/v1/submissions/${submissionId}/review`;
};

export const reviewQuestSubmission = async (
  submissionId: string,
  reviewSubmissionRequest: ReviewSubmissionRequest,
  options?: RequestInit
): Promise<reviewQuestSubmissionResponse> => {
  return customInstance<reviewQuestSubmissionResponse>(getReviewQuestSubmissionUrl(submissionId), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(reviewSubmissionRequest),
  });
};

/**
 * Called via API Gateway after successful sign-in/sign-up. Upserts into `users` table using asserted user identity from the gateway token subject (`X-Gateway-Auth`) and provided email.

 * @summary Ensure current user exists in Neon (idempotent upsert)
 */
export type ensureUserResponse200 = {
  data: EnsureUserResponse;
  status: 200;
};

export type ensureUserResponse400 = {
  data: BadRequestResponse;
  status: 400;
};

export type ensureUserResponse401 = {
  data: UnauthorizedResponse;
  status: 401;
};

export type ensureUserResponse500 = {
  data: InternalErrorResponse;
  status: 500;
};

export type ensureUserResponse503 = {
  data: ServiceAuthNotConfiguredResponse;
  status: 503;
};

export type ensureUserResponseSuccess = ensureUserResponse200 & {
  headers: Headers;
};
export type ensureUserResponseError = (
  | ensureUserResponse400
  | ensureUserResponse401
  | ensureUserResponse500
  | ensureUserResponse503
) & {
  headers: Headers;
};

export type ensureUserResponse = ensureUserResponseSuccess | ensureUserResponseError;

export const getEnsureUserUrl = () => {
  return `/v1/users/ensure`;
};

export const ensureUser = async (
  ensureUserRequest: EnsureUserRequest,
  options?: RequestInit
): Promise<ensureUserResponse> => {
  return customInstance<ensureUserResponse>(getEnsureUserUrl(), {
    ...options,
    method: "POST",
    headers: { "Content-Type": "application/json", ...options?.headers },
    body: JSON.stringify(ensureUserRequest),
  });
};
