/**
 * Rielt.Market Asia - Mock Listings
 * Демо-данные объявлений о жилье для разработки
 */

import type { Listing } from './types';

/**
 * Фиксированные ID для демо-объявлений
 * Используются фиксированные ID для стабильных URL
 */

/**
 * Демо-объявления о жилье
 */
export const mockListings: Listing[] = [
  // Бангкок, Таиланд
  {
    id: 'studio-bangkok-silom',
    title: 'Современная студия в центре Бангкока',
    description: 'Уютная студия в самом сердце Бангкока, рядом с BTS станция. Полностью оборудованная кухня, кондиционер, Wi-Fi. Идеально для цифровых кочевников. Рядом кафе, коворкинги, магазины.',
    type: 'studio',
    rentalType: 'short-term',
    address: {
      country: 'Таиланд',
      city: 'Бангкок',
      district: 'Силом',
      street: 'Sukhumvit Road',
      coordinates: { lat: 13.7304, lng: 100.5413 },
    },
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    bedrooms: 0,
    beds: 1,
    bathrooms: 1,
    area: 35,
    maxGuests: 2,
    pricing: {
      perNight: 25,
      currency: 'USD',
      cleaningFee: 10,
      serviceFee: 5,
    },
    amenities: {
      wifi: true,
      workspace: true,
      kitchen: true,
      ac: true,
      washingMachine: false,
      parking: false,
    },
    houseRules: {
      smoking: false,
      pets: false,
      parties: false,
      minStay: 3,
      checkIn: '14:00',
      checkOut: '11:00',
    },
    availability: {
      calendar: {},
      instantBooking: true,
    },
    owner: {
      id: 'owner1',
      name: 'Анна Петрова',
      avatar: 'https://i.pravatar.cc/150?img=1',
      isRFPartner: true,
      rating: 4.8,
      responseTime: 'В течение часа',
      joinedAt: '2024-01-15T00:00:00Z',
    },
    isRF: true,
    rfVoucher: {
      id: 'voucher1',
      title: 'Скидка 10% для русскоязычных',
      description: 'Специальное предложение для участников Go2Asia',
      discount: 10,
      conditions: 'При бронировании от 7 ночей',
      validFrom: '2025-01-01T00:00:00Z',
      validUntil: '2025-12-31T23:59:59Z',
      usageLimit: 100,
      usedCount: 23,
    },
    proVerification: {
      verified: true,
      verifiedBy: 'pro1',
      verifiedAt: '2025-01-10T00:00:00Z',
      checklist: {
        photosMatch: true,
        condition: true,
        description: true,
        noise: true,
        internet: true,
      },
    },
    isNew: false,
    isInstant: true,
    rating: 4.7,
    reviewsCount: 45,
    viewsCount: 320,
    savesCount: 18,
    createdAt: '2025-10-27T00:00:00Z',
    updatedAt: '2025-11-22T00:00:00Z',
    status: 'approved',
  },
  {
    id: 'apartment-bangkok-asoke',
    title: 'Просторные апартаменты с видом на город',
    description: 'Современные апартаменты в новом жилом комплексе. 2 спальни, полностью оборудованная кухня, стиральная машина. Бассейн и фитнес-зал в здании. Рядом метро и торговый центр.',
    type: 'apartment',
    rentalType: 'long-term',
    address: {
      country: 'Таиланд',
      city: 'Бангкок',
      district: 'Асоке',
      coordinates: { lat: 13.7367, lng: 100.5608 },
    },
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    area: 85,
    maxGuests: 4,
    pricing: {
      perMonth: 1200,
      currency: 'USD',
      deposit: 600,
    },
    amenities: {
      wifi: true,
      workspace: true,
      kitchen: true,
      ac: true,
      washingMachine: true,
      parking: true,
      pool: true,
      gym: true,
      elevator: true,
    },
    houseRules: {
      smoking: false,
      pets: true,
      parties: false,
      minStay: 30,
      checkIn: '15:00',
      checkOut: '12:00',
    },
    longTermConditions: {
      minMonths: 1,
      maxMonths: 12,
      deposit: 600,
      utilities: 'separate',
    },
    owner: {
      id: 'owner2',
      name: 'Михаил Соколов',
      avatar: 'https://i.pravatar.cc/150?img=2',
      rating: 4.9,
      responseTime: 'В течение 2 часов',
      joinedAt: '2023-11-20T00:00:00Z',
    },
    isRF: false,
    isNew: true,
    rating: 4.8,
    reviewsCount: 12,
    viewsCount: 156,
    savesCount: 8,
    createdAt: '2025-11-20T00:00:00Z',
    updatedAt: '2025-11-26T00:00:00Z',
    status: 'approved',
  },
  {
    id: 'coliving-bangkok-thonburi',
    title: 'Co-living пространство для номадов',
    description: 'Современное co-living пространство в центре Бангкока. Отдельная комната с общей кухней и гостиной. Отличное место для работы: быстрый интернет, рабочие зоны, коворкинг рядом.',
    type: 'coliving',
    rentalType: 'short-term',
    address: {
      country: 'Таиланд',
      city: 'Бангкок',
      district: 'Тхонбури',
      coordinates: { lat: 13.7244, lng: 100.4930 },
    },
    photos: [
      'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800',
      'https://images.unsplash.com/photo-1522771739844-6a9f47d2b330?w=800',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1556912172-45b7abe8b7e1?w=800',
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    area: 20,
    maxGuests: 1,
    pricing: {
      perNight: 18,
      currency: 'USD',
      cleaningFee: 5,
    },
    amenities: {
      wifi: true,
      workspace: true,
      kitchen: true,
      ac: true,
      washingMachine: true,
    },
    houseRules: {
      smoking: false,
      pets: false,
      parties: false,
      minStay: 7,
      checkIn: '15:00',
      checkOut: '11:00',
    },
    availability: {
      calendar: {},
      instantBooking: true,
    },
    owner: {
      id: 'owner3',
      name: 'Елена Ковалева',
      avatar: 'https://i.pravatar.cc/150?img=3',
      isPRO: true,
      rating: 5.0,
      responseTime: 'В течение 30 минут',
      joinedAt: '2024-03-10T00:00:00Z',
    },
    proVerification: {
      verified: true,
      verifiedBy: 'pro2',
      verifiedAt: '2025-01-05T00:00:00Z',
      checklist: {
        photosMatch: true,
        condition: true,
        description: true,
        noise: true,
        internet: true,
      },
    },
    isNew: false,
    isInstant: true,
    rating: 4.9,
    reviewsCount: 67,
    viewsCount: 445,
    savesCount: 34,
    createdAt: '2025-09-27T00:00:00Z',
    updatedAt: '2025-11-17T00:00:00Z',
    status: 'approved',
  },
  // Пхукет, Таиланд
  {
    id: 'villa-phuket-kata',
    title: 'Вилла у пляжа с бассейном',
    description: 'Роскошная вилла в 50 метрах от пляжа. 3 спальни, бассейн, терраса с видом на море. Идеально для семьи или компании друзей. Рядом рестораны, магазины, развлечения.',
    type: 'house',
    rentalType: 'short-term',
    address: {
      country: 'Таиланд',
      city: 'Пхукет',
      district: 'Ката',
      coordinates: { lat: 7.8804, lng: 98.3923 },
    },
    photos: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
    bedrooms: 3,
    beds: 4,
    bathrooms: 3,
    area: 180,
    maxGuests: 6,
    pricing: {
      perNight: 120,
      currency: 'USD',
      cleaningFee: 30,
      serviceFee: 15,
    },
    amenities: {
      wifi: true,
      kitchen: true,
      ac: true,
      washingMachine: true,
      parking: true,
      pool: true,
      childFriendly: true,
      petsAllowed: true,
    },
    houseRules: {
      smoking: false,
      pets: true,
      parties: true,
      minStay: 5,
      checkIn: '15:00',
      checkOut: '11:00',
    },
    availability: {
      calendar: {},
      instantBooking: false,
    },
    owner: {
      id: 'owner4',
      name: 'Дмитрий Волков',
      avatar: 'https://i.pravatar.cc/150?img=4',
      isRFPartner: true,
      rating: 4.6,
      responseTime: 'В течение 3 часов',
      joinedAt: '2023-09-15T00:00:00Z',
    },
    isRF: true,
    rfVoucher: {
      id: 'voucher2',
      title: 'Бесплатная уборка при бронировании от 10 ночей',
      description: 'Специальное предложение для участников Go2Asia',
      discountAmount: 30,
      conditions: 'При бронировании от 10 ночей',
      validFrom: '2025-01-01T00:00:00Z',
      validUntil: '2025-12-31T23:59:59Z',
      usageLimit: 50,
      usedCount: 12,
    },
    isNew: false,
    isInstant: false,
    rating: 4.5,
    reviewsCount: 28,
    viewsCount: 567,
    savesCount: 45,
    createdAt: '2025-08-28T00:00:00Z',
    updatedAt: '2025-11-12T00:00:00Z',
    status: 'approved',
  },
  {
    id: 'studio-phuket-rawai',
    title: 'Студия в тихом районе Пхукета',
    description: 'Уютная студия в тихом районе, но недалеко от пляжа. Подходит для долгосрочной аренды. Рядом супермаркет, кафе, транспорт.',
    type: 'studio',
    rentalType: 'long-term',
    address: {
      country: 'Таиланд',
      city: 'Пхукет',
      district: 'Раваи',
      coordinates: { lat: 7.8500, lng: 98.3833 },
    },
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    bedrooms: 0,
    beds: 1,
    bathrooms: 1,
    area: 30,
    maxGuests: 2,
    pricing: {
      perMonth: 450,
      currency: 'USD',
      deposit: 450,
    },
    amenities: {
      wifi: true,
      kitchen: true,
      ac: true,
      washingMachine: false,
    },
    houseRules: {
      smoking: false,
      pets: false,
      parties: false,
      minStay: 30,
      checkIn: '14:00',
      checkOut: '11:00',
    },
    longTermConditions: {
      minMonths: 3,
      maxMonths: 12,
      deposit: 450,
      utilities: 'separate',
    },
    owner: {
      id: 'owner5',
      name: 'Ольга Новикова',
      rating: 4.7,
      responseTime: 'В течение дня',
      joinedAt: '2024-02-01T00:00:00Z',
    },
    isRF: false,
    isNew: false,
    rating: 4.6,
    reviewsCount: 8,
    viewsCount: 89,
    savesCount: 5,
    createdAt: '2025-07-29T00:00:00Z',
    updatedAt: '2025-11-07T00:00:00Z',
    status: 'approved',
  },
  // Бали, Индонезия
  {
    id: 'apartment-bali-ubud',
    title: 'Апартаменты в Убуде с видом на рисовые поля',
    description: 'Просторные апартаменты в спокойном Убуде. 2 спальни, большая терраса с видом на рисовые поля. Рядом йога-студии, кафе, магазины. Идеально для долгосрочной аренды.',
    type: 'apartment',
    rentalType: 'long-term',
    address: {
      country: 'Индонезия',
      city: 'Бали',
      district: 'Убуд',
      coordinates: { lat: -8.5069, lng: 115.2625 },
    },
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    bedrooms: 2,
    beds: 2,
    bathrooms: 2,
    area: 95,
    maxGuests: 4,
    pricing: {
      perMonth: 800,
      currency: 'USD',
      deposit: 800,
    },
    amenities: {
      wifi: true,
      workspace: true,
      kitchen: true,
      ac: true,
      washingMachine: true,
      parking: true,
      balcony: true,
    },
    houseRules: {
      smoking: false,
      pets: false,
      parties: false,
      minStay: 30,
      checkIn: '14:00',
      checkOut: '11:00',
    },
    longTermConditions: {
      minMonths: 1,
      maxMonths: 12,
      deposit: 800,
      utilities: 'included',
    },
    owner: {
      id: 'owner6',
      name: 'Александр Морозов',
      avatar: 'https://i.pravatar.cc/150?img=5',
      isRFPartner: true,
      isPRO: true,
      rating: 4.9,
      responseTime: 'В течение часа',
      joinedAt: '2023-12-01T00:00:00Z',
    },
    isRF: true,
    proVerification: {
      verified: true,
      verifiedBy: 'pro3',
      verifiedAt: '2025-01-08T00:00:00Z',
      checklist: {
        photosMatch: true,
        condition: true,
        description: true,
        noise: true,
        internet: true,
      },
      notes: 'Отличное место для работы удалённо. Быстрый интернет подтверждён.',
    },
    isNew: false,
    rating: 4.8,
    reviewsCount: 34,
    viewsCount: 234,
    savesCount: 19,
    createdAt: '2025-09-12T00:00:00Z',
    updatedAt: '2025-11-19T00:00:00Z',
    status: 'approved',
  },
  {
    id: 'room-bali-canggu',
    title: 'Комната в доме в Чангу',
    description: 'Отдельная комната в доме в Чангу, районе цифровых кочевников. Общая кухня и гостиная. Рядом пляж, коворкинги, кафе. Подходит для краткосрочной аренды.',
    type: 'room',
    rentalType: 'short-term',
    address: {
      country: 'Индонезия',
      city: 'Бали',
      district: 'Чангу',
      coordinates: { lat: -8.6833, lng: 115.1333 },
    },
    photos: [
      'https://images.unsplash.com/photo-1522771739844-6a9f47d2b330?w=800',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1522771739844-6a9f47d2b330?w=800',
    bedrooms: 1,
    beds: 1,
    bathrooms: 1,
    area: 15,
    maxGuests: 1,
    pricing: {
      perNight: 20,
      currency: 'USD',
      cleaningFee: 5,
    },
    amenities: {
      wifi: true,
      workspace: true,
      kitchen: true,
      ac: true,
    },
    houseRules: {
      smoking: false,
      pets: false,
      parties: false,
      minStay: 7,
      checkIn: '14:00',
      checkOut: '11:00',
    },
    availability: {
      calendar: {},
      instantBooking: true,
    },
    owner: {
      id: 'owner7',
      name: 'Мария Смирнова',
      rating: 4.5,
      responseTime: 'В течение 2 часов',
      joinedAt: '2024-04-20T00:00:00Z',
    },
    isRF: false,
    isNew: true,
    isInstant: true,
    rating: 4.4,
    reviewsCount: 15,
    viewsCount: 123,
    savesCount: 7,
    createdAt: '2025-11-13T00:00:00Z',
    updatedAt: '2025-11-25T00:00:00Z',
    status: 'approved',
  },
  // Хошимин, Вьетнам
  {
    id: 'studio-hochiminh-district1',
    title: 'Современная студия в центре Хошимина',
    description: 'Новая студия в центре Хошимина, район 1. Полностью оборудованная кухня, кондиционер, Wi-Fi. Рядом метро, кафе, магазины. Идеально для краткосрочной аренды.',
    type: 'studio',
    rentalType: 'short-term',
    address: {
      country: 'Вьетнам',
      city: 'Хошимин',
      district: 'Район 1',
      coordinates: { lat: 10.7769, lng: 106.7009 },
    },
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    bedrooms: 0,
    beds: 1,
    bathrooms: 1,
    area: 32,
    maxGuests: 2,
    pricing: {
      perNight: 22,
      currency: 'USD',
      cleaningFee: 8,
      serviceFee: 4,
    },
    amenities: {
      wifi: true,
      workspace: true,
      kitchen: true,
      ac: true,
      washingMachine: false,
    },
    houseRules: {
      smoking: false,
      pets: false,
      parties: false,
      minStay: 3,
      checkIn: '14:00',
      checkOut: '11:00',
    },
    availability: {
      calendar: {},
      instantBooking: true,
    },
    owner: {
      id: 'owner8',
      name: 'Иван Кузнецов',
      avatar: 'https://i.pravatar.cc/150?img=6',
      isRFPartner: true,
      rating: 4.7,
      responseTime: 'В течение часа',
      joinedAt: '2024-01-10T00:00:00Z',
    },
    isRF: true,
    isNew: false,
    isInstant: true,
    rating: 4.6,
    reviewsCount: 23,
    viewsCount: 178,
    savesCount: 12,
    createdAt: '2025-10-12T00:00:00Z',
    updatedAt: '2025-11-20T00:00:00Z',
    status: 'approved',
  },
  // Куала-Лумпур, Малайзия
  {
    id: 'apartment-kuala-lumpur-klcc',
    title: 'Апартаменты в KLCC с видом на башни',
    description: 'Роскошные апартаменты в районе KLCC с видом на башни Петронас. 2 спальни, полностью оборудованная кухня, стиральная машина. Бассейн и фитнес-зал в здании.',
    type: 'apartment',
    rentalType: 'long-term',
    address: {
      country: 'Малайзия',
      city: 'Куала-Лумпур',
      district: 'KLCC',
      coordinates: { lat: 3.1577, lng: 101.7123 },
    },
    photos: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
    bedrooms: 2,
    beds: 3,
    bathrooms: 2,
    area: 110,
    maxGuests: 4,
    pricing: {
      perMonth: 1500,
      currency: 'USD',
      deposit: 1500,
    },
    amenities: {
      wifi: true,
      workspace: true,
      kitchen: true,
      ac: true,
      washingMachine: true,
      parking: true,
      pool: true,
      gym: true,
      elevator: true,
      security: true,
    },
    houseRules: {
      smoking: false,
      pets: false,
      parties: false,
      minStay: 30,
      checkIn: '15:00',
      checkOut: '12:00',
    },
    longTermConditions: {
      minMonths: 1,
      maxMonths: 12,
      deposit: 1500,
      utilities: 'separate',
    },
    owner: {
      id: 'owner9',
      name: 'Сергей Лебедев',
      rating: 4.8,
      responseTime: 'В течение 2 часов',
      joinedAt: '2023-10-05T00:00:00Z',
    },
    isRF: false,
    isNew: false,
    rating: 4.7,
    reviewsCount: 19,
    viewsCount: 267,
    savesCount: 15,
    createdAt: '2025-08-18T00:00:00Z',
    updatedAt: '2025-11-15T00:00:00Z',
    status: 'approved',
  },
  // Сингапур
  {
    id: 'studio-singapore-orchard',
    title: 'Компактная студия в центре Сингапура',
    description: 'Компактная, но уютная студия в самом центре Сингапура. Рядом метро, кафе, магазины. Подходит для краткосрочной аренды. Полностью оборудована всем необходимым.',
    type: 'studio',
    rentalType: 'short-term',
    address: {
      country: 'Сингапур',
      city: 'Сингапур',
      district: 'Орчард',
      coordinates: { lat: 1.3048, lng: 103.8318 },
    },
    photos: [
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    ],
    coverPhoto: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
    bedrooms: 0,
    beds: 1,
    bathrooms: 1,
    area: 28,
    maxGuests: 2,
    pricing: {
      perNight: 65,
      currency: 'USD',
      cleaningFee: 15,
      serviceFee: 8,
    },
    amenities: {
      wifi: true,
      workspace: true,
      kitchen: true,
      ac: true,
      washingMachine: false,
    },
    houseRules: {
      smoking: false,
      pets: false,
      parties: false,
      minStay: 5,
      checkIn: '15:00',
      checkOut: '11:00',
    },
    availability: {
      calendar: {},
      instantBooking: false,
    },
    owner: {
      id: 'owner10',
      name: 'Екатерина Федорова',
      avatar: 'https://i.pravatar.cc/150?img=7',
      isRFPartner: true,
      rating: 4.9,
      responseTime: 'В течение часа',
      joinedAt: '2024-02-15T00:00:00Z',
    },
    isRF: true,
    proVerification: {
      verified: true,
      verifiedBy: 'pro4',
      verifiedAt: '2025-01-12T00:00:00Z',
      checklist: {
        photosMatch: true,
        condition: true,
        description: true,
        noise: true,
        internet: true,
      },
    },
    isNew: false,
    isInstant: false,
    rating: 4.8,
    reviewsCount: 31,
    viewsCount: 412,
    savesCount: 28,
    createdAt: '2025-10-02T00:00:00Z',
    updatedAt: '2025-11-21T00:00:00Z',
    status: 'approved',
  },
];

