/**
 * @go2asia/types
 * 
 * Auto-generated TypeScript types from OpenAPI specifications.
 * 
 * This file is auto-generated by Orval. Do not edit manually.
 * Run `pnpm gen:types` to regenerate.
 */

// Types will be generated here by Orval
export {};





