import { Event } from './types';

/**
 * Демо-данные событий для Pulse Asia
 * Используются в календаре и на страницах деталей событий
 */
export const mockEvents: Event[] = [
  // Начало ноября (1-10)
  {
    id: '101',
    title: 'Фестиваль воздушных змеев',
    description: 'Традиционный фестиваль запуска воздушных змеев на пляже. Приходите всей семьёй!',
    startDate: new Date('2025-11-01T15:00:00'),
    endDate: new Date('2025-11-01T18:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/2901209/pexels-photo-2901209.jpeg',
    location: {
      name: 'Пляж Чавенг',
      address: 'Чавенг, Самуи',
      city: 'Самуи',
      country: 'Таиланд',
      placeId: 'chaweng-beach-samui',
    },
    attendeesCount: 80,
    category: 'Культура',
    tags: ['фестиваль', 'семья', 'традиции'],
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'local',
    scale: 'city',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-samui',
      name: 'Samui Cultural Center',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'samui',
      placeId: 'chaweng-beach-samui',
    },
  },
  {
    id: '102',
    title: 'Урок дайвинга для начинающих',
    description: 'Первое погружение с аквалангом под руководством сертифицированного инструктора PADI. Всё оборудование включено.',
    startDate: new Date('2025-11-02T09:00:00'),
    endDate: new Date('2025-11-02T12:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/1007657/pexels-photo-1007657.jpeg',
    location: {
      name: 'Дайв-центр Phuket',
      address: 'Патонг, Пхукет',
      city: 'Пхукет',
      country: 'Таиланд',
      placeId: 'dive-center-phuket',
    },
    attendeesCount: 4,
    maxAttendees: 6,
    category: 'Спорт',
    tags: ['дайвинг', 'море', 'приключения'],
    badges: ['verified'],
    price: { type: 'paid', amount: 3500, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-dive',
      name: 'Phuket Dive Center',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'phuket',
      placeId: 'dive-center-phuket',
    },
  },
  {
    id: '103',
    title: 'Концерт живой музыки',
    description: 'Выступление местной рок-группы "Saigon Rocks" в баре на набережной.',
    startDate: new Date('2025-11-02T20:00:00'),
    endDate: new Date('2025-11-02T23:00:00'),
    timezone: 'Asia/Ho_Chi_Minh',
    cover: 'https://images.pexels.com/photos/1105666/pexels-photo-1105666.jpeg',
    location: {
      name: 'Rock Bar Saigon',
      address: 'Район 1, Хошимин',
      city: 'Хошимин',
      country: 'Вьетнам',
      placeId: 'rock-bar-saigon',
    },
    attendeesCount: 50,
    category: 'Музыка',
    tags: ['рок', 'концерт', 'живая музыка'],
    badges: ['verified'],
    price: { type: 'paid', amount: 150000, currency: 'VND' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-rockbar',
      name: 'Rock Bar Saigon',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'vietnam',
      cityId: 'ho-chi-minh',
      placeId: 'rock-bar-saigon',
    },
  },
  {
    id: '104',
    title: 'Завтрак с предпринимателями',
    description: 'Networking-завтрак для основателей стартапов и инвесторов. Обмен опытом и установление контактов.',
    startDate: new Date('2025-11-04T08:00:00'),
    endDate: new Date('2025-11-04T10:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg',
    location: {
      name: 'Hub Bangkok',
      address: 'Sukhumvit Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'hub-bangkok',
    },
    attendeesCount: 15,
    maxAttendees: 20,
    category: 'IT',
    tags: ['нетворкинг', 'стартапы', 'бизнес'],
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'en',
    scale: 'city',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-hub',
      name: 'Hub Bangkok',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'hub-bangkok',
    },
  },
  {
    id: '105',
    title: 'Кулинарный мастер-класс: Вьетнамская кухня',
    description: 'Учимся готовить фо, бань ми и спринг-роллы с опытным шеф-поваром.',
    startDate: new Date('2025-11-05T14:00:00'),
    endDate: new Date('2025-11-05T17:00:00'),
    timezone: 'Asia/Ho_Chi_Minh',
    cover: 'https://images.pexels.com/photos/1640774/pexels-photo-1640774.jpeg',
    location: {
      name: 'Vietnam Cooking Class',
      address: 'Старый квартал, Ханой',
      city: 'Ханой',
      country: 'Вьетнам',
      placeId: 'vietnam-cooking-hanoi',
    },
    attendeesCount: 10,
    maxAttendees: 15,
    category: 'Еда',
    tags: ['кулинария', 'вьетнамская кухня', 'мастер-класс'],
    badges: ['verified', 'russian-friendly'],
    price: { type: 'paid', amount: 800000, currency: 'VND' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    verified: true,
    russianFriendly: true,
    organizer: {
      id: 'org-viet-cook',
      name: 'Vietnam Cooking Class',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'vietnam',
      cityId: 'hanoi',
      placeId: 'vietnam-cooking-hanoi',
    },
  },
  {
    id: '106',
    title: 'Детский праздник в парке',
    description: 'Игры, конкурсы и развлечения для детей всех возрастов. Аниматоры, угощения, подарки.',
    startDate: new Date('2025-11-07T10:00:00'),
    endDate: new Date('2025-11-07T14:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/1547813/pexels-photo-1547813.jpeg',
    location: {
      name: 'Парк Benjakitti',
      address: 'Сукхумвит, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'benjakitti-park',
    },
    attendeesCount: 40,
    category: 'Семья',
    tags: ['дети', 'праздник', 'семья'],
    badges: ['free', 'russian-friendly'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    russianFriendly: true,
    organizer: {
      id: 'org-rf-community',
      name: 'Russian Family Community Bangkok',
      type: 'pro',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'benjakitti-park',
    },
  },
  {
    id: '107',
    title: 'Вечеринка на крыше: Sunset Party',
    description: 'Встреча заката с коктейлями и диджей-сетом. Панорамный вид на город.',
    startDate: new Date('2025-11-08T18:00:00'),
    endDate: new Date('2025-11-08T22:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/2263436/pexels-photo-2263436.jpeg',
    location: {
      name: 'Octave Rooftop',
      address: 'Silom, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'octave-rooftop',
    },
    attendeesCount: 120,
    category: 'Ночная жизнь',
    tags: ['закат', 'коктейли', 'музыка'],
    badges: ['verified'],
    price: { type: 'paid', amount: 400, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-octave',
      name: 'Octave Rooftop Lounge',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'octave-rooftop',
    },
  },
  {
    id: '108',
    title: 'Экскурсия по рисовым террасам',
    description: 'Пешеходная экскурсия по живописным рисовым террасам Бали с гидом.',
    startDate: new Date('2025-11-09T08:00:00'),
    endDate: new Date('2025-11-09T14:00:00'),
    timezone: 'Asia/Jakarta',
    cover: 'https://images.pexels.com/photos/2491286/pexels-photo-2491286.jpeg',
    location: {
      name: 'Tegallalang Rice Terraces',
      address: 'Убуд, Бали',
      city: 'Убуд',
      country: 'Индонезия',
      placeId: 'tegallalang-terraces',
    },
    attendeesCount: 12,
    category: 'Культура',
    tags: ['экскурсия', 'природа', 'фото'],
    badges: ['verified'],
    price: { type: 'paid', amount: 400000, currency: 'IDR' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-bali-tours',
      name: 'Bali Cultural Tours',
      type: 'pro',
    },
    atlasLinks: {
      countryId: 'indonesia',
      cityId: 'ubud',
      placeId: 'tegallalang-terraces',
    },
  },
  {
    id: '109',
    title: 'Воскресный бранч с джазом',
    description: 'Бранч-меню и живая джазовая музыка в саду. Отличное место для воскресного отдыха.',
    startDate: new Date('2025-11-10T11:00:00'),
    endDate: new Date('2025-11-10T15:00:00'),
    timezone: 'Asia/Singapore',
    cover: 'https://images.pexels.com/photos/1267697/pexels-photo-1267697.jpeg',
    location: {
      name: 'Jazz Garden',
      address: 'Орчард, Сингапур',
      city: 'Сингапур',
      country: 'Сингапур',
      placeId: 'jazz-garden',
    },
    attendeesCount: 35,
    category: 'Еда',
    tags: ['бранч', 'джаз', 'воскресенье'],
    badges: ['verified'],
    price: { type: 'paid', amount: 60, currency: 'SGD' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-jazz-garden',
      name: 'Jazz Garden Singapore',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'singapore',
      cityId: 'singapore',
      placeId: 'jazz-garden',
    },
  },
  
  // Середина ноября (11-20)
  {
    id: '110',
    title: 'Утренняя пробежка в парке',
    description: 'Групповая пробежка на 5 км с разминкой и растяжкой. Подходит для всех уровней.',
    startDate: new Date('2025-11-11T06:30:00'),
    endDate: new Date('2025-11-11T07:30:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/2803158/pexels-photo-2803158.jpeg',
    location: {
      name: 'Парк Чатучак',
      address: 'Чатучак, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'chatuchak-park',
    },
    attendeesCount: 25,
    category: 'Спорт',
    tags: ['бег', 'утро', 'здоровье'],
    badges: ['free'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    organizer: {
      id: 'org-runners',
      name: 'Bangkok Runners Club',
      type: 'pro',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'chatuchak-park',
    },
  },
  {
    id: '111',
    title: 'Workshop: Фотография путешествий',
    description: 'Мастер-класс по мобильной фотографии для путешественников. Теория и практика.',
    startDate: new Date('2025-11-12T15:00:00'),
    endDate: new Date('2025-11-12T18:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/1983037/pexels-photo-1983037.jpeg',
    location: {
      name: 'Creative Space',
      address: 'Ari, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'creative-space-ari',
    },
    attendeesCount: 8,
    maxAttendees: 12,
    category: 'Образование',
    tags: ['фотография', 'обучение', 'творчество'],
    badges: ['verified', 'russian-friendly'],
    price: { type: 'paid', amount: 800, currency: 'THB' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    verified: true,
    russianFriendly: true,
    organizer: {
      id: 'org-photo',
      name: 'Travel Photography School',
      type: 'pro',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'creative-space-ari',
    },
  },
  {
    id: '112',
    title: 'Традиционный танец: мастер-класс',
    description: 'Изучаем традиционные тайские танцы с профессиональными танцорами.',
    startDate: new Date('2025-11-13T17:00:00'),
    endDate: new Date('2025-11-13T19:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/3894381/pexels-photo-3894381.jpeg',
    location: {
      name: 'Культурный центр',
      address: 'Старый город, Чиангмай',
      city: 'Чиангмай',
      country: 'Таиланд',
      placeId: 'cultural-center-cm',
    },
    attendeesCount: 15,
    category: 'Культура',
    tags: ['танцы', 'традиции', 'культура'],
    badges: ['verified'],
    price: { type: 'paid', amount: 500, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-culture-cm',
      name: 'Chiang Mai Cultural Center',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'chiang-mai',
      placeId: 'cultural-center-cm',
    },
  },
  {
    id: '113',
    title: 'Hackathon: AI & ML',
    description: '24-часовой хакатон по искусственному интеллекту и машинному обучению. Призы и менторство.',
    startDate: new Date('2025-11-14T09:00:00'),
    endDate: new Date('2025-11-15T09:00:00'),
    timezone: 'Asia/Singapore',
    cover: 'https://images.pexels.com/photos/1181675/pexels-photo-1181675.jpeg',
    location: {
      name: 'Tech Hub Singapore',
      address: 'Раффлз Плейс, Сингапур',
      city: 'Сингапур',
      country: 'Сингапур',
      placeId: 'tech-hub-sg',
    },
    attendeesCount: 80,
    maxAttendees: 100,
    category: 'IT',
    tags: ['хакатон', 'AI', 'ML', 'разработка'],
    badges: ['verified'],
    price: { type: 'paid', amount: 50, currency: 'SGD' },
    language: 'en',
    scale: 'city',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-tech-sg',
      name: 'Singapore Tech Community',
      type: 'pro',
    },
    atlasLinks: {
      countryId: 'singapore',
      cityId: 'singapore',
      placeId: 'tech-hub-sg',
    },
  },
  {
    id: '114',
    title: 'Фермерский рынок',
    description: 'Органические продукты от местных фермеров, крафтовая еда и напитки.',
    startDate: new Date('2025-11-15T08:00:00'),
    endDate: new Date('2025-11-15T13:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/264537/pexels-photo-264537.jpeg',
    location: {
      name: 'Lumpini Park',
      address: 'Lumpini, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'lumpini-park',
    },
    attendeesCount: 200,
    category: 'Еда',
    tags: ['рынок', 'фермеры', 'органика'],
    badges: ['free', 'repeating'],
    price: { type: 'free' },
    language: 'local',
    scale: 'city',
    status: 'published',
    organizer: {
      id: 'org-farmers',
      name: 'Bangkok Farmers Market',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'lumpini-park',
    },
  },
  {
    id: '115',
    title: 'Семейный пикник: Праздник осени',
    description: 'Пикник для семей с детьми с играми и конкурсами.',
    startDate: new Date('2025-11-16T10:00:00'),
    endDate: new Date('2025-11-16T15:00:00'),
    timezone: 'Asia/Ho_Chi_Minh',
    cover: 'https://images.pexels.com/photos/2253879/pexels-photo-2253879.jpeg',
    location: {
      name: 'Tao Dan Park',
      address: 'Район 1, Хошимин',
      city: 'Хошимин',
      country: 'Вьетнам',
      placeId: 'tao-dan-park',
    },
    attendeesCount: 60,
    category: 'Семья',
    tags: ['пикник', 'семья', 'дети'],
    badges: ['free', 'russian-friendly'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    russianFriendly: true,
    organizer: {
      id: 'org-family-hcm',
      name: 'Russian Families Ho Chi Minh',
      type: 'pro',
    },
    atlasLinks: {
      countryId: 'vietnam',
      cityId: 'ho-chi-minh',
      placeId: 'tao-dan-park',
    },
  },
  {
    id: '116',
    title: 'Кинопоказ под звёздами',
    description: 'Показ классических фильмов на открытом воздухе под звёздным небом.',
    startDate: new Date('2025-11-17T19:30:00'),
    endDate: new Date('2025-11-17T22:30:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg',
    location: {
      name: 'Rooftop Cinema',
      address: 'Thonglor, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'rooftop-cinema',
    },
    attendeesCount: 40,
    maxAttendees: 50,
    category: 'Культура',
    tags: ['кино', 'вечер', 'крыша'],
    badges: ['verified'],
    price: { type: 'paid', amount: 250, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-cinema',
      name: 'Rooftop Cinema Bangkok',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'rooftop-cinema',
    },
  },
  {
    id: '117',
    title: 'Медитация и звуковая терапия',
    description: 'Сессия медитации с поющими чашами и звуковая терапия для глубокого расслабления.',
    startDate: new Date('2025-11-18T18:00:00'),
    endDate: new Date('2025-11-18T19:30:00'),
    timezone: 'Asia/Jakarta',
    cover: 'https://images.pexels.com/photos/3822583/pexels-photo-3822583.jpeg',
    location: {
      name: 'Yoga Barn',
      address: 'Убуд, Бали',
      city: 'Убуд',
      country: 'Индонезия',
      placeId: 'yoga-barn',
    },
    attendeesCount: 20,
    category: 'Культура',
    tags: ['медитация', 'релакс', 'звукотерапия'],
    badges: ['verified'],
    price: { type: 'paid', amount: 150000, currency: 'IDR' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-yoga-barn',
      name: 'Yoga Barn Ubud',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'indonesia',
      cityId: 'ubud',
      placeId: 'yoga-barn',
    },
  },
  {
    id: '118',
    title: 'Электронная музыка: DJ Night',
    description: 'Выступление известного диджея из Европы. Ночь электронной музыки.',
    startDate: new Date('2025-11-19T22:00:00'),
    endDate: new Date('2025-11-20T03:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/1763075/pexels-photo-1763075.jpeg',
    location: {
      name: 'Beam Club',
      address: 'Ekkamai, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'beam-club',
    },
    attendeesCount: 250,
    category: 'Ночная жизнь',
    tags: ['электроника', 'клуб', 'ночь'],
    badges: ['verified'],
    price: { type: 'paid', amount: 600, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-beam',
      name: 'Beam Club Bangkok',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'beam-club',
    },
  },
  {
    id: '119',
    title: 'Велопрогулка по городу',
    description: 'Организованная велопрогулка по историческим местам Бангкока с гидом.',
    startDate: new Date('2025-11-20T07:00:00'),
    endDate: new Date('2025-11-20T10:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/100582/pexels-photo-100582.jpeg',
    location: {
      name: 'Старый город',
      address: 'Раттанакосин, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'old-town-bangkok',
    },
    attendeesCount: 18,
    maxAttendees: 25,
    category: 'Спорт',
    tags: ['велосипед', 'экскурсия', 'история'],
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-bike',
      name: 'Bangkok Bike Tours',
      type: 'pro',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'old-town-bangkok',
    },
  },
  {
    id: '120',
    title: 'Джазовый вечер в кафе',
    description: 'Живая джазовая музыка в уютном кафе с видом на реку.',
    startDate: new Date('2025-11-21T20:00:00'),
    endDate: new Date('2025-11-21T23:00:00'),
    timezone: 'Asia/Ho_Chi_Minh',
    cover: 'https://images.pexels.com/photos/1047442/pexels-photo-1047442.jpeg',
    location: {
      name: 'Jazz Cafe Saigon',
      address: 'Набережная, Хошимин',
      city: 'Хошимин',
      country: 'Вьетнам',
      placeId: 'jazz-cafe-saigon',
    },
    attendeesCount: 30,
    category: 'Музыка',
    tags: ['джаз', 'кафе', 'вечер'],
    badges: ['verified'],
    price: { type: 'paid', amount: 100000, currency: 'VND' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-jazz-cafe',
      name: 'Jazz Cafe Saigon',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'vietnam',
      cityId: 'ho-chi-minh',
      placeId: 'jazz-cafe-saigon',
    },
  },
  {
    id: '121',
    title: 'Фестиваль кофе',
    description: 'Дегустация лучших сортов кофе из Вьетнама и мастер-классы бариста.',
    startDate: new Date('2025-11-22T10:00:00'),
    endDate: new Date('2025-11-22T18:00:00'),
    timezone: 'Asia/Ho_Chi_Minh',
    cover: 'https://images.pexels.com/photos/302899/pexels-photo-302899.jpeg',
    location: {
      name: 'Центральная площадь',
      address: 'Ханой',
      city: 'Ханой',
      country: 'Вьетнам',
      placeId: 'central-square-hanoi',
    },
    attendeesCount: 300,
    category: 'Еда',
    tags: ['кофе', 'фестиваль', 'дегустация'],
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'local',
    scale: 'city',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-coffee',
      name: 'Vietnam Coffee Association',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'vietnam',
      cityId: 'hanoi',
      placeId: 'central-square-hanoi',
    },
  },
  
  // Текущая неделя (23-29 ноября)
  {
    id: '1',
    title: 'Утренняя йога на пляже',
    description: 'Йога-сессия на рассвете с видом на море. Подходит для всех уровней подготовки.',
    startDate: new Date('2025-11-23T06:00:00'),
    endDate: new Date('2025-11-23T07:30:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/1472887/pexels-photo-1472887.jpeg',
    location: {
      name: 'Пляж Ката',
      address: 'Пляж Ката, Пхукет',
      city: 'Пхукет',
      country: 'Таиланд',
      placeId: 'kata-beach-phuket',
    },
    attendeesCount: 12,
    category: 'Спорт',
    tags: ['йога', 'утро', 'пляж', 'здоровье'],
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-1',
      name: 'Yoga Phuket Community',
      type: 'pro',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'phuket',
      placeId: 'kata-beach-phuket',
    },
  },
  {
    id: '2',
    title: 'Встреча Digital Nomads',
    description: 'Еженедельная встреча удалённых работников. Обмен опытом, нетворкинг, кофе.',
    startDate: new Date('2025-11-23T19:00:00'),
    endDate: new Date('2025-11-23T21:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/1181406/pexels-photo-1181406.jpeg',
    location: {
      name: 'Кофейня "Кофе и Код"',
      address: 'Sukhumvit Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'coffee-code-bangkok',
    },
    attendeesCount: 28,
    category: 'IT',
    tags: ['digital nomads', 'нетворкинг', 'коворкинг'],
    badges: ['free', 'russian-friendly'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    russianFriendly: true,
    organizer: {
      id: 'org-nomads',
      name: 'Digital Nomads Bangkok',
      type: 'pro',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'coffee-code-bangkok',
    },
  },
  {
    id: '3',
    title: 'Фестиваль уличной еды',
    description: 'Гастрономический фестиваль с участием лучших уличных поваров Бангкока.',
    startDate: new Date('2025-11-24T17:00:00'),
    endDate: new Date('2025-11-24T23:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/1552641/pexels-photo-1552641.jpeg',
    location: {
      name: 'Чайна-таун',
      address: 'Yaowarat Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'chinatown-bangkok',
    },
    attendeesCount: 150,
    category: 'Еда',
    tags: ['уличная еда', 'фестиваль', 'гастрономия'],
    badges: ['verified', 'russian-friendly'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    verified: true,
    russianFriendly: true,
    organizer: {
      id: 'org-street-food',
      name: 'Bangkok Street Food Association',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'chinatown-bangkok',
    },
  },
  {
    id: '4',
    title: 'Концерт джаз-бэнда',
    description: 'Живая музыка в атмосферном джаз-клубе. Выступление местных музыкантов.',
    startDate: new Date('2025-11-24T20:00:00'),
    endDate: new Date('2025-11-25T00:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/1864637/pexels-photo-1864637.jpeg',
    location: {
      name: 'Jazz Club Bangkok',
      address: 'Sukhumvit Soi 11, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'jazz-club-bangkok',
    },
    attendeesCount: 45,
    category: 'Музыка',
    tags: ['джаз', 'концерт', 'клуб'],
    badges: ['verified'],
    price: { type: 'paid', amount: 300, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-jazz',
      name: 'Jazz Club Bangkok',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'jazz-club-bangkok',
    },
  },
  {
    id: '5',
    title: 'Мастер-класс по тайской кухне',
    description: 'Учимся готовить пад тай, том ям и другие классические блюда тайской кухни.',
    startDate: new Date('2025-11-25T10:00:00'),
    endDate: new Date('2025-11-25T13:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg',
    location: {
      name: 'Cooking School Bangkok',
      address: 'Silom Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'cooking-school-bangkok',
    },
    attendeesCount: 8,
    maxAttendees: 12,
    category: 'Еда',
    tags: ['кулинария', 'тайская кухня', 'мастер-класс'],
    badges: ['verified', 'russian-friendly'],
    price: { type: 'paid', amount: 1200, currency: 'THB' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    verified: true,
    russianFriendly: true,
    organizer: {
      id: 'org-2',
      name: 'Cooking School Bangkok',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'cooking-school-bangkok',
    },
  },
  {
    id: '6',
    title: 'Ночной рынок в Чиангмае',
    description: 'Еженедельный ночной рынок с местными ремеслами, едой и развлечениями.',
    startDate: new Date('2025-11-25T18:00:00'),
    endDate: new Date('2025-11-25T23:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/2087391/pexels-photo-2087391.jpeg',
    location: {
      name: 'Sunday Walking Street',
      address: 'Ratchadamnoen Road, Чиангмай',
      city: 'Чиангмай',
      country: 'Таиланд',
      placeId: 'sunday-market-cm',
    },
    attendeesCount: 200,
    category: 'Культура',
    tags: ['рынок', 'ремесла', 'еда'],
    badges: ['free', 'repeating'],
    price: { type: 'free' },
    language: 'local',
    scale: 'city',
    status: 'published',
    organizer: {
      id: 'org-market-cm',
      name: 'Chiang Mai Tourism',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'chiang-mai',
      placeId: 'sunday-market-cm',
    },
  },
  {
    id: '7',
    title: 'Семейный пикник в парке',
    description: 'Пикник для семей с детьми. Игры, конкурсы, угощения.',
    startDate: new Date('2025-11-26T11:00:00'),
    endDate: new Date('2025-11-26T15:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/2253870/pexels-photo-2253870.jpeg',
    location: {
      name: 'Лумпини парк',
      address: 'Лумпини парк, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'lumpini-park',
    },
    attendeesCount: 35,
    category: 'Семья',
    tags: ['пикник', 'семья', 'дети'],
    badges: ['free', 'russian-friendly'],
    price: { type: 'free' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    russianFriendly: true,
    organizer: {
      id: 'org-family-bkk',
      name: 'Russian Family Club Bangkok',
      type: 'pro',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'lumpini-park',
    },
  },
  {
    id: '8',
    title: 'Технический митап: React и Next.js',
    description: 'Доклады о современных подходах к разработке на React и Next.js.',
    startDate: new Date('2025-11-26T19:30:00'),
    endDate: new Date('2025-11-26T22:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/1181263/pexels-photo-1181263.jpeg',
    location: {
      name: 'WeWork Thonglor',
      address: 'Thonglor Soi 10, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'wework-thonglor',
    },
    attendeesCount: 42,
    category: 'IT',
    tags: ['React', 'Next.js', 'frontend'],
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'en',
    scale: 'city',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-react',
      name: 'React Bangkok Community',
      type: 'pro',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'wework-thonglor',
    },
  },
  {
    id: '9',
    title: 'Экскурсия по храмам',
    description: 'Пешеходная экскурсия по главным храмам Бангкока с русскоязычным гидом.',
    startDate: new Date('2025-11-27T09:00:00'),
    endDate: new Date('2025-11-27T13:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/911738/pexels-photo-911738.jpeg',
    location: {
      name: 'Храм Изумрудного Будды',
      address: 'Grand Palace, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'grand-palace-bangkok',
    },
    attendeesCount: 15,
    category: 'Культура',
    tags: ['храмы', 'экскурсия', 'история'],
    badges: ['verified', 'russian-friendly'],
    price: { type: 'paid', amount: 800, currency: 'THB' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    verified: true,
    russianFriendly: true,
    organizer: {
      id: 'org-tours',
      name: 'Bangkok Tours Russia',
      type: 'pro',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'grand-palace-bangkok',
    },
  },
  {
    id: '10',
    title: 'Вечеринка на крыше',
    description: 'Закат на крыше с коктейлями и живой музыкой. Dress code: casual.',
    startDate: new Date('2025-11-27T18:00:00'),
    endDate: new Date('2025-11-28T01:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/761854/pexels-photo-761854.jpeg',
    location: {
      name: 'Sky Bar',
      address: 'Lebua Hotel, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'sky-bar-lebua',
    },
    attendeesCount: 60,
    category: 'Ночная жизнь',
    tags: ['закат', 'коктейли', 'крыша'],
    badges: ['verified'],
    price: { type: 'paid', amount: 500, currency: 'THB' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-skybar',
      name: 'Sky Bar Lebua',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'sky-bar-lebua',
    },
  },
  {
    id: '11',
    title: 'Серфинг на Бали',
    description: 'Групповой урок серфинга для начинающих. Все необходимое оборудование включено.',
    startDate: new Date('2025-11-28T08:00:00'),
    endDate: new Date('2025-11-28T11:00:00'),
    timezone: 'Asia/Jakarta',
    cover: 'https://images.pexels.com/photos/390051/surfer-wave-sunset-the-indian-ocean-390051.jpeg',
    location: {
      name: 'Пляж Кута',
      address: 'Пляж Кута, Бали',
      city: 'Кута',
      country: 'Индонезия',
      placeId: 'kuta-beach-bali',
    },
    attendeesCount: 6,
    category: 'Спорт',
    tags: ['серфинг', 'море', 'спорт'],
    badges: ['verified'],
    price: { type: 'paid', amount: 250000, currency: 'IDR' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-surf',
      name: 'Bali Surf School',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'indonesia',
      cityId: 'kuta',
      placeId: 'kuta-beach-bali',
    },
  },
  {
    id: '12',
    title: 'Фестиваль фонарей',
    description: 'Традиционный фестиваль фонарей в Чиангмае. Тысячи фонарей в небе.',
    startDate: new Date('2025-11-28T19:00:00'),
    endDate: new Date('2025-11-28T23:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/2255441/pexels-photo-2255441.jpeg',
    location: {
      name: 'Центр Чиангмая',
      address: 'Центральная площадь, Чиангмай',
      city: 'Чиангмай',
      country: 'Таиланд',
      placeId: 'central-cm',
    },
    attendeesCount: 500,
    category: 'Культура',
    tags: ['фонари', 'фестиваль', 'традиции'],
    badges: ['verified', 'free'],
    price: { type: 'free' },
    language: 'local',
    scale: 'city',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-lantern',
      name: 'Chiang Mai Festival Committee',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'chiang-mai',
      placeId: 'central-cm',
    },
  },
  {
    id: '13',
    title: 'Бранч в русском ресторане',
    description: 'Воскресный бранч с блинчиками, икрой и традиционными русскими блюдами.',
    startDate: new Date('2025-11-29T11:00:00'),
    endDate: new Date('2025-11-29T15:00:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/1109197/pexels-photo-1109197.jpeg',
    location: {
      name: 'Русский дом',
      address: 'Sukhumvit Soi 24, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'russian-house',
    },
    attendeesCount: 25,
    category: 'Еда',
    tags: ['русская кухня', 'бранч', 'воскресенье'],
    badges: ['russian-friendly', 'verified'],
    price: { type: 'paid', amount: 600, currency: 'THB' },
    language: 'ru',
    scale: 'place',
    status: 'published',
    verified: true,
    russianFriendly: true,
    organizer: {
      id: 'org-russian',
      name: 'Русский Дом Бангкок',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'russian-house',
    },
  },
  {
    id: '14',
    title: 'Концерт традиционной музыки',
    description: 'Выступление местных музыкантов с традиционными инструментами Вьетнама.',
    startDate: new Date('2025-11-29T20:00:00'),
    endDate: new Date('2025-11-29T22:00:00'),
    timezone: 'Asia/Ho_Chi_Minh',
    cover: 'https://images.pexels.com/photos/3769112/pexels-photo-3769112.jpeg',
    location: {
      name: 'Ханойская опера',
      address: '1 Trang Tien, Ханой',
      city: 'Ханой',
      country: 'Вьетнам',
      placeId: 'hanoi-opera',
    },
    attendeesCount: 80,
    category: 'Культура',
    tags: ['музыка', 'традиции', 'концерт'],
    badges: ['verified'],
    price: { type: 'paid', amount: 200000, currency: 'VND' },
    language: 'local',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-opera',
      name: 'Hanoi Opera House',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'vietnam',
      cityId: 'hanoi',
      placeId: 'hanoi-opera',
    },
  },
  
  // Конец ноября (30)
  {
    id: '15',
    title: 'Мастер-класс по медитации',
    description: 'Групповая медитация в храме. Подходит для начинающих.',
    startDate: new Date('2025-11-30T07:00:00'),
    endDate: new Date('2025-11-30T08:30:00'),
    timezone: 'Asia/Bangkok',
    cover: 'https://images.pexels.com/photos/1051838/pexels-photo-1051838.jpeg',
    location: {
      name: 'Храм Ват Пхо',
      address: 'Sanam Chai Road, Бангкок',
      city: 'Бангкок',
      country: 'Таиланд',
      placeId: 'wat-pho',
    },
    attendeesCount: 20,
    category: 'Культура',
    tags: ['медитация', 'храм', 'духовность'],
    badges: ['free', 'verified'],
    price: { type: 'free' },
    language: 'en',
    scale: 'place',
    status: 'published',
    verified: true,
    organizer: {
      id: 'org-watpho',
      name: 'Wat Pho Temple',
      type: 'partner',
    },
    atlasLinks: {
      countryId: 'thailand',
      cityId: 'bangkok',
      placeId: 'wat-pho',
    },
  },
  {
    id: '16',
    title: 'Фуд-тур по Сингапуру',
    description: 'Гастрономический тур по лучшим уличным закусочным Сингапура.',
    startDate: new Date('2025-11-30T17:00:00'),
    endDate: new Date('2025-11-30T21:00:00'),
    timezone: 'Asia/Singapore',
    cover: 'https://images.pexels.com/photos/1484516/pexels-photo-1484516.jpeg',
    location: {
      name: 'Чайна-таун',
      address: 'Chinatown, Сингапур',
      city: 'Сингапур',
      country: 'Сингапур',
      placeId: 'chinatown-sg',
    },
    attendeesCount: 12,
    category: 'Еда',
    tags: ['фуд-тур', 'улич ная еда', 'гастрономия'],
    badges: ['verified', 'russian-friendly'],
    price: { type: 'paid', amount: 80, currency: 'SGD' },
    language: 'ru',
    scale: 'city',
    status: 'published',
    verified: true,
    russianFriendly: true,
    organizer: {
      id: 'org-foodtour',
      name: 'Singapore Food Tours',
      type: 'pro',
    },
    atlasLinks: {
      countryId: 'singapore',
      cityId: 'singapore',
      placeId: 'chinatown-sg',
    },
  },
];

// Конвертируем массив в Record для быстрого доступа по ID
export const mockEventsById: Record<string, Event> = mockEvents.reduce((acc, event) => {
  acc[event.id] = event;
  return acc;
}, {} as Record<string, Event>);

