/**
 * Quest Asia - Mock Quests
 * Демо-данные квестов для разработки
 */

import type { Quest, NFTBadge, QuestSeason } from './types';

/**
 * Сезон квестов
 */
export const currentSeason: QuestSeason = {
  id: 'season-winter-2025',
  name: 'Зимний сезон 2025',
  description: 'Исследуйте ЮВА в зимние месяцы',
  startDate: new Date('2025-12-01'),
  endDate: new Date('2026-02-28'),
  theme: 'winter',
};

/**
 * NFT-бейджи
 */
export const mockNFTBadges: NFTBadge[] = [
  {
    id: 'temple-runner',
    name: 'Temple Runner',
    description: 'Посетил 5 храмов',
    image: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73a6e?w=200',
    rarity: 'rare',
    category: 'temple',
    requirements: {
      questsCompleted: 5,
      specificQuests: ['temple-tour-bangkok', 'wat-pho-discovery'],
    },
  },
  {
    id: 'street-food-hero',
    name: 'Street Food Hero',
    description: 'Прошёл 3 квеста про еду',
    image: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=200',
    rarity: 'epic',
    category: 'food',
    requirements: {
      questsCompleted: 3,
      specificQuests: ['street-food-bangkok', 'night-market-phuket'],
    },
  },
  {
    id: 'night-market-pro',
    name: 'Night Market Pro',
    description: 'Прошёл 5 ночных квестов',
    image: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=200',
    rarity: 'legendary',
    category: 'nightlife',
    requirements: {
      questsCompleted: 5,
    },
  },
];

/**
 * Демо-квесты
 */
export const mockQuests: Quest[] = [
  // Бангкок - Маршрут
  {
    id: 'temple-tour-bangkok',
    title: 'Храмовый тур по Бангкоку',
    description: 'Посетите 3 самых известных храма Бангкока и узнайте их историю',
    coverPhoto: 'https://images.unsplash.com/photo-1539650116574-75c0c6d73a6e?w=800',
    type: 'route',
    duration: 120,
    difficulty: 'medium',
    city: 'Бангкок',
    district: 'Старый город',
    country: 'Таиланд',
    badges: [
      { type: 'rf', label: 'RF' },
      { type: 'offline', label: 'Офлайн' },
    ],
    rewards: {
      points: 500,
      nftBadges: [mockNFTBadges[0]],
      conditions: {
        minCheckpoints: 3,
      },
    },
    steps: [
      {
        id: 'step-1-wat-pho',
        order: 1,
        type: 'geo-checkin',
        title: 'Храм Ват Пхо',
        description: 'Доберитесь до храма Ват Пхо и отметьтесь на месте',
        placeId: 'wat-pho-bangkok',
        coordinates: { lat: 13.7464, lng: 100.4931 },
        radius: 50,
        rewards: { points: 100 },
        validation: { skipAllowed: false, skipPenalty: 0 },
      },
      {
        id: 'step-2-wat-pho-quiz',
        order: 2,
        type: 'quiz',
        title: 'Викторина о Ват Пхо',
        description: 'Ответьте на вопросы о храме',
        questions: [
          {
            id: 'q1',
            question: 'В каком году был основан храм Ват Пхо?',
            options: ['1688', '1782', '1851', '1920'],
            correctAnswer: 0,
            hint: 'Храм был основан в эпоху Аюттхаи',
          },
          {
            id: 'q2',
            question: 'Сколько ступ находится в храме?',
            options: ['91', '99', '108', '120'],
            correctAnswer: 1,
          },
        ],
        rewards: { points: 150 },
        validation: { skipAllowed: true, skipPenalty: 50 },
      },
      {
        id: 'step-3-wat-arun',
        order: 3,
        type: 'geo-checkin',
        title: 'Храм Ват Арун',
        description: 'Посетите храм Ват Арун (Храм Рассвета)',
        placeId: 'wat-arun-bangkok',
        coordinates: { lat: 13.7438, lng: 100.4889 },
        radius: 50,
        rewards: { points: 100 },
        validation: { skipAllowed: false, skipPenalty: 0 },
      },
      {
        id: 'step-4-wat-arun-photo',
        order: 4,
        type: 'photo',
        title: 'Фото у храма',
        description: 'Сделайте фото на фоне храма Ват Арун',
        mediaType: 'photo',
        minMediaCount: 1,
        moderationRequired: false,
        rewards: { points: 100 },
        validation: { skipAllowed: true, skipPenalty: 30 },
      },
      {
        id: 'step-5-grand-palace',
        order: 5,
        type: 'geo-checkin',
        title: 'Большой дворец',
        description: 'Завершите тур посещением Большого дворца',
        placeId: 'grand-palace-bangkok',
        coordinates: { lat: 13.7500, lng: 100.4915 },
        radius: 100,
        rewards: { points: 150 },
        validation: { skipAllowed: false, skipPenalty: 0 },
      },
    ],
    startPoint: {
      placeId: 'wat-pho-bangkok',
      coordinates: { lat: 13.7464, lng: 100.4931 },
      address: '2 Sanam Chai Rd, Phra Borom Maha Ratchawang, Phra Nakhon, Bangkok 10200',
    },
    bestTime: 'morning',
    preparation: ['Удобная обувь', 'Вода', 'Солнцезащитный крем'],
    season: currentSeason,
    offlineAvailable: true,
    createdAt: new Date('2025-11-01'),
    updatedAt: new Date('2025-11-15'),
    stats: {
      completions: 234,
      averageRating: 4.7,
      averageTime: 115,
    },
  },
  // Бангкок - Чек-ин
  {
    id: 'street-food-bangkok',
    title: 'Уличная еда Бангкока',
    description: 'Попробуйте лучшие блюда уличной еды в Бангкоке',
    coverPhoto: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
    type: 'checkin',
    duration: 90,
    difficulty: 'easy',
    city: 'Бангкок',
    district: 'Чайна-таун',
    country: 'Таиланд',
    badges: [
      { type: 'rf', label: 'RF' },
    ],
    rewards: {
      points: 300,
      nftBadges: [mockNFTBadges[1]],
    },
    steps: [
      {
        id: 'step-1-pad-thai',
        order: 1,
        type: 'task',
        title: 'Попробуйте Pad Thai',
        description: 'Закажите Pad Thai в одном из RF-ресторанов',
        taskDescription: 'Закажите Pad Thai и получите код подтверждения',
        confirmationMethod: 'code',
        placeId: 'pad-thai-restaurant',
        coordinates: { lat: 13.7400, lng: 100.5100 },
        radius: 100,
        rewards: { points: 80 },
        validation: { skipAllowed: false, skipPenalty: 0 },
      },
      {
        id: 'step-2-mango-sticky-rice',
        order: 2,
        type: 'task',
        title: 'Манго с клейким рисом',
        description: 'Попробуйте десерт манго с клейким рисом',
        taskDescription: 'Закажите манго с клейким рисом',
        confirmationMethod: 'photo',
        placeId: 'mango-stall',
        coordinates: { lat: 13.7450, lng: 100.5150 },
        radius: 50,
        rewards: { points: 70 },
        validation: { skipAllowed: true, skipPenalty: 20 },
      },
      {
        id: 'step-3-tom-yum',
        order: 3,
        type: 'task',
        title: 'Том Ям',
        description: 'Попробуйте знаменитый суп Том Ям',
        taskDescription: 'Закажите Том Ям и сделайте фото',
        confirmationMethod: 'photo',
        placeId: 'tom-yum-restaurant',
        coordinates: { lat: 13.7500, lng: 100.5200 },
        radius: 100,
        rewards: { points: 100 },
        validation: { skipAllowed: false, skipPenalty: 0 },
      },
    ],
    startPoint: {
      coordinates: { lat: 13.7400, lng: 100.5100 },
      address: 'Yaowarat Rd, Samphanthawong, Bangkok 10100',
    },
    bestTime: 'evening',
    preparation: ['Аппетит', 'Вода'],
    offlineAvailable: true,
    createdAt: new Date('2025-11-05'),
    updatedAt: new Date('2025-11-20'),
    stats: {
      completions: 456,
      averageRating: 4.9,
      averageTime: 85,
    },
  },
  // Пхукет - Контент
  {
    id: 'phuket-beaches',
    title: 'Пляжи Пхукета',
    description: 'Создайте фото-коллекцию самых красивых пляжей Пхукета',
    coverPhoto: 'https://images.unsplash.com/photo-1559827260-dc66d52bef19?w=800',
    type: 'content',
    duration: 180,
    difficulty: 'medium',
    city: 'Пхукет',
    district: 'Ката',
    country: 'Таиланд',
    badges: [
      { type: 'offline', label: 'Офлайн' },
    ],
    rewards: {
      points: 600,
      nftBadges: [],
    },
    steps: [
      {
        id: 'step-1-kata-beach',
        order: 1,
        type: 'photo',
        title: 'Пляж Ката',
        description: 'Сделайте фото на пляже Ката',
        mediaType: 'photo',
        minMediaCount: 1,
        moderationRequired: false,
        placeId: 'kata-beach',
        coordinates: { lat: 7.8200, lng: 98.3000 },
        radius: 200,
        rewards: { points: 150 },
        validation: { skipAllowed: false, skipPenalty: 0 },
      },
      {
        id: 'step-2-karon-beach',
        order: 2,
        type: 'photo',
        title: 'Пляж Карон',
        description: 'Сделайте фото на пляже Карон',
        mediaType: 'photo',
        minMediaCount: 1,
        moderationRequired: false,
        placeId: 'karon-beach',
        coordinates: { lat: 7.8400, lng: 98.2900 },
        radius: 200,
        rewards: { points: 150 },
        validation: { skipAllowed: true, skipPenalty: 50 },
      },
      {
        id: 'step-3-patong-beach',
        order: 3,
        type: 'photo',
        title: 'Пляж Патонг',
        description: 'Сделайте фото на пляже Патонг',
        mediaType: 'photo',
        minMediaCount: 1,
        moderationRequired: false,
        placeId: 'patong-beach',
        coordinates: { lat: 7.8800, lng: 98.2900 },
        radius: 200,
        rewards: { points: 150 },
        validation: { skipAllowed: true, skipPenalty: 50 },
      },
      {
        id: 'step-4-sunset-video',
        order: 4,
        type: 'video',
        title: 'Видео заката',
        description: 'Снимите видео заката на одном из пляжей',
        mediaType: 'video',
        minMediaCount: 1,
        moderationRequired: true,
        rewards: { points: 200 },
        validation: { skipAllowed: true, skipPenalty: 100 },
      },
    ],
    startPoint: {
      coordinates: { lat: 7.8200, lng: 98.3000 },
      address: 'Kata Beach, Phuket',
    },
    bestTime: 'afternoon',
    preparation: ['Камера', 'Солнцезащитный крем'],
    offlineAvailable: true,
    createdAt: new Date('2025-11-10'),
    updatedAt: new Date('2025-11-25'),
    stats: {
      completions: 189,
      averageRating: 4.8,
      averageTime: 170,
    },
  },
  // Чиангмай - Событие
  {
    id: 'chiangmai-night-market',
    title: 'Ночной рынок Чиангмая',
    description: 'Посетите знаменитый ночной рынок и примите участие в событиях',
    coverPhoto: 'https://images.unsplash.com/photo-1514933651103-005eec06c04b?w=800',
    type: 'event',
    duration: 120,
    difficulty: 'easy',
    city: 'Чиангмай',
    district: 'Старый город',
    country: 'Таиланд',
    badges: [
      { type: 'rf', label: 'RF' },
      { type: 'night', label: 'Ночь' },
      { type: 'offline', label: 'Офлайн' },
    ],
    rewards: {
      points: 400,
      nftBadges: [mockNFTBadges[2]],
    },
    steps: [
      {
        id: 'step-1-market-entry',
        order: 1,
        type: 'geo-checkin',
        title: 'Вход на рынок',
        description: 'Доберитесь до ночного рынка',
        placeId: 'chiangmai-night-market',
        coordinates: { lat: 18.7886, lng: 98.9950 },
        radius: 100,
        rewards: { points: 50 },
        validation: { skipAllowed: false, skipPenalty: 0 },
      },
      {
        id: 'step-2-pulse-event',
        order: 2,
        type: 'pulse-event',
        title: 'Посетите событие',
        description: 'Примите участие в событии на рынке',
        eventId: 'night-market-concert',
        rewards: { points: 150 },
        validation: { skipAllowed: true, skipPenalty: 50 },
      },
      {
        id: 'step-3-qr-code',
        order: 3,
        type: 'qr-code',
        title: 'QR-код партнёра',
        description: 'Отсканируйте QR-код у RF-партнёра',
        qrCode: 'RF-CHIANGMAI-NIGHT-2025',
        code: 'RF-CHIANGMAI-NIGHT-2025',
        rewards: { points: 100 },
        validation: { skipAllowed: false, skipPenalty: 0 },
      },
      {
        id: 'step-4-market-photo',
        order: 4,
        type: 'photo',
        title: 'Фото рынка',
        description: 'Сделайте фото ночного рынка',
        mediaType: 'photo',
        minMediaCount: 1,
        moderationRequired: false,
        rewards: { points: 100 },
        validation: { skipAllowed: true, skipPenalty: 30 },
      },
    ],
    startPoint: {
      placeId: 'chiangmai-night-market',
      coordinates: { lat: 18.7886, lng: 98.9950 },
      address: 'Wua Lai Rd, Tambon Hai Ya, Mueang Chiang Mai District, Chiang Mai 50100',
    },
    bestTime: 'night',
    preparation: ['Наличные', 'Камера'],
    season: currentSeason,
    offlineAvailable: true,
    createdAt: new Date('2025-11-08'),
    updatedAt: new Date('2025-11-22'),
    stats: {
      completions: 312,
      averageRating: 4.6,
      averageTime: 110,
    },
  },
  // Бали - Маршрут
  {
    id: 'bali-temples-route',
    title: 'Маршрут храмов Бали',
    description: 'Посетите священные храмы Бали и узнайте их историю',
    coverPhoto: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=800',
    type: 'route',
    duration: 240,
    difficulty: 'hard',
    city: 'Бали',
    district: 'Убуд',
    country: 'Индонезия',
    badges: [
      { type: 'offline', label: 'Офлайн' },
    ],
    rewards: {
      points: 800,
      nftBadges: [mockNFTBadges[0]],
    },
    steps: [
      {
        id: 'step-1-tanah-lot',
        order: 1,
        type: 'geo-checkin',
        title: 'Храм Танах Лот',
        description: 'Посетите храм Танах Лот на скале',
        placeId: 'tanah-lot-temple',
        coordinates: { lat: -8.6211, lng: 115.0869 },
        radius: 100,
        rewards: { points: 200 },
        validation: { skipAllowed: false, skipPenalty: 0 },
      },
      {
        id: 'step-2-ulun-danu',
        order: 2,
        type: 'geo-checkin',
        title: 'Храм Улун Дану',
        description: 'Посетите храм Улун Дану на озере Братан',
        placeId: 'ulun-danu-temple',
        coordinates: { lat: -8.2747, lng: 115.1667 },
        radius: 100,
        rewards: { points: 200 },
        validation: { skipAllowed: false, skipPenalty: 0 },
      },
      {
        id: 'step-3-besakih',
        order: 3,
        type: 'geo-checkin',
        title: 'Храм Бесаких',
        description: 'Посетите главный храм Бали - Бесаких',
        placeId: 'besakih-temple',
        coordinates: { lat: -8.2744, lng: 115.4500 },
        radius: 150,
        rewards: { points: 250 },
        validation: { skipAllowed: false, skipPenalty: 0 },
      },
      {
        id: 'step-4-temple-quiz',
        order: 4,
        type: 'quiz',
        title: 'Викторина о храмах',
        description: 'Ответьте на вопросы о храмах Бали',
        questions: [
          {
            id: 'q1',
            question: 'Сколько храмов входит в комплекс Бесаких?',
            options: ['18', '23', '30', '35'],
            correctAnswer: 1,
          },
        ],
        rewards: { points: 150 },
        validation: { skipAllowed: true, skipPenalty: 75 },
      },
    ],
    startPoint: {
      placeId: 'tanah-lot-temple',
      coordinates: { lat: -8.6211, lng: 115.0869 },
      address: 'Beraban, Kediri, Tabanan Regency, Bali',
    },
    bestTime: 'morning',
    preparation: ['Транспорт', 'Вода', 'Солнцезащитный крем'],
    offlineAvailable: true,
    createdAt: new Date('2025-11-12'),
    updatedAt: new Date('2025-11-26'),
    stats: {
      completions: 145,
      averageRating: 4.9,
      averageTime: 230,
    },
  },
];

